### ISSUE TITLE
Cant see the tab EPG Grabber Modules in the graphic interface

### ISSUE THREAD

**Issue by reptilbud** [linuxserver/docker-tvheadend#102]
As said in the title, I cant see the tab EPG Grabber Modules in the graphic interface but everything else appears to work fine... Any idea ?

(Run docker in an ubuntu)

Thanks

**Comment by j0nnymoe** [comment]
Enabled the advanced view in settings.

**Comment by reptilbud** [comment]
Thanks a lot I was doing so inside the view directly not inside the settings pane
