### ISSUE TITLE
Latest Versions - IPTV Automatic Network no longer works

### ISSUE THREAD

**Issue by restalfep** [linuxserver/docker-tvheadend#112]
After updating to the latest docker TVHeadEnd no longer works on my Synology NAS using docker. As soon as I downgrade back to an older version like Stable 4.2 then it works again. I am using it via IPTV Automatic Network and the initial scan won't even work, can't via any channels. The Scan says "scan no data, failed" or something along those lines.

**Comment by aptalca** [comment]
Did you forget to add a message?

**Comment by restalfep** [comment]
As a seperate test, I tried enabling "Use A/V Library" and although the scans say things like: 2019-02-17 02:45:13.403 libav: AVBSFContext: Invalid NAL unit 0, skipping.
2019-02-17 02:45:13.419 libav: AVBSFContext: Invalid NAL unit 0, skipping.

The actual scan shows it completed properly. No idea if that helps since it's way over my head.

**Comment by tobbenb** [comment]
Do you use a playlist for the automatic IPTV network?

**Comment by restalfep** [comment]
Yes I use host networking, and I entered the m3u url under Automatic IPTV Network.

It was the same setup as with older builds and never had this issue before. Currently I'm using the SynoCommunity Package as well and it has no problems. Very strange....

**Comment by tobbenb** [comment]
What is the source? 
Please add more info as there isn't much info to go on other than it's not working.

**Comment by restalfep** [comment]
I understand, not really sure what information I can provide if anything particular let me know. I've tried debugging it for many hours now and got nowhere. The source is from IPTV-EPG, m3u link similar to http://iptv-epg.com/dXXX-asdfjkl.m3u . I also tried using the m3u link directly from my provider but same problem both ways. Older versions work so I'm assuming something in the newest builds is not compatible with my system for some reason (Synology DS918+) or a setting is changed that I need to change back. I have been debugging for so long been tearing my hair out, but no idea what to even try at this point or what information will be helpful to you.

**Comment by tobbenb** [comment]
How about a log?
From what you describe, you are scanning the muxes often?

**Comment by restalfep** [comment]
Do I need to enable the log to make it write to a file so I can post it here? I have just been using the bottom of the screen dialog but obviously not ideal. 

I see some settings under Debugging / Settings regarding syslog and such, assuming I need to enable/set that up for it to actually write the log files?

**Comment by tobbenb** [comment]
Yes, you need to specify the logfile and choose the appropriate parts to debug. It's specified in Help.

**Comment by restalfep** [comment]
Ok I will work on that next. Just taking a break since I've been working on this for 5-6 hours... not thinking clearly at the moment.... Will do that when I resume to try and nail this down. Thanks

**Comment by restalfep** [comment]
Strange... so I restarted everything from scratch again, got debugging ready, and then everything just worked... I'll mark this as closed. Thanks

**Comment by tobbenb** [comment]
Good you got it running again :)
