### ISSUE TITLE
Need to add a file to /usr/sbin to grab xml EPG

### ISSUE THREAD

**Issue by Benoire** [linuxserver/docker-tvheadend#122]
Hi

I'm attempting to move over from the synology NAS native TVH install to your docker image.  To access IPTV in NZ via TVH I need to install a new XML grabber in to /usr/sbin however I do not see a /usr/ folder in the /config folder on the NAS that the container is assigned to use.

Is it possible to get /usr/ folder exported to the config folder so that I can do this?  If not, what is the best way to inject this in to the docker image and keep it there when it is updated?

Thanks,

Chris

**Comment by aptalca** [comment]
You can map the file in via docker run `-v /path/to/your/file:/usr/sbin/file`

**Comment by j0nnymoe** [comment]
best thing to do is see if you can get this XML grabber submitted upstream and if it does, it'll get automatically included within our tvheadend images.

**Comment by tobbenb** [comment]
You need to add it in /usr/bin, as that is where tvheadend looks for grabbers.

**Comment by thelamer** [comment]
Closing as we are not going to make the requested change but their are workarounds notes in this issue.
