### ISSUE TITLE
No HD Channels with Alpine 3.9

### ISSUE THREAD

**Issue by fat-fred** [linuxserver/docker-tvheadend#130]
With the New Image (with alpine 3.9 as base) no hd channels works for me. 
If i change the baseimage to alpine 3.8 back. Everything work like bevor. 

In Kodi it says „No free Adapter“. Tvheadend only says „Restarting Channel ...“.  

Adapter is a PCTV 461e. My docker Runs on a synology (x64)

Any idea what i can do?

**Comment by CHBMB** [comment]
Is this still an issue on Alpine 3.10?  If so please let us know and I'll reopen it.
