### ISSUE TITLE
tv_grab_uk_tvguide - Can't call method "look_down" on an undefined value

### ISSUE THREAD

**Issue by UnR34L** [linuxserver/docker-tvheadend#132]
I followed the blog post and it mentioned using the internal grabber, tv_grab_uk_tvguide.

When I run:
```
docker exec -it -u abc tvheadend /usr/bin/tv_grab_uk_tvguide --configure
```
I get the error
```
Can't call method "look_down" on an undefined value at /usr/bin/tv_grab_uk_tvguide line 758.
```

**Comment by rasmusbe** [comment]
It's a bug in the XMLTV package (https://github.com/XMLTV/xmltv/issues/64) but they haven't released a new version yet. You can replace the broken version with the version here: https://github.com/XMLTV/xmltv/blob/master/grab/uk_tvguide/tv_grab_uk_tvguide

**Comment by UnR34L** [comment]
Ah ok, thanks for info.

**Comment by Media38** [comment]
With tv_grab_fr the same error occurs at line 425.
I insert these lines at line 423 :
    if (not defined $grid) {
        return;
    }
it seems OK?
That is right ?
