### ISSUE TITLE
Recording time range setting

### ISSUE THREAD

**Issue by ralfi** [linuxserver/docker-tvheadend#141]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

HTS Tvheadend 4.3-1804~gebb096804
Build: 4.3-1804~gebb096804 (2019-09-20T04:52:00+0200)

With this building time range defining for auto recordings ( prior / after ) do not work - this will not recorgnized by TVH. 

docker script:

docker container create --name=tvheadend -e PUID=0 -e PGUID=0 -e TZ=Europe/Berlin -p 9981:9981 -p 9982:9982 -v /var/lib/tvheadend/config/:/config -v /mnt/test/tvheadend/:/recordings --network=mein_Netzwerk --hostname=tvsrv -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro --ip=172.18.1.5 --restart unless-stopped linuxserver/tvheadend:latest

**Comment by tobbenb** [comment]
Might be an upstream issue. Try using an older tag. You can find those on docker hub.
Also, don't run the container as root. That always leads to issues.

**Comment by ralfi** [comment]
Thanks, there is a mistake in the upstream.
