### ISSUE TITLE
Feature request : ccextractor

### ISSUE THREAD

**Issue by jefflessard** [linuxserver/docker-tvheadend#145]
Can you please include ccextractor in your tvheadend build?

This would allow closed caption extraction in tvh recording's post processing.

[CCExtractor on github](https://github.com/CCExtractor/ccextractor)

Instead of compiling from scratch, it could be copied from existing docker images as a static linked executable. If you prefer to compile it too (dynamically linked libs).

### Copying from existing docker image - No OCR support (static link)
https://hub.docker.com/r/skmendez/static-ccextractor
`
COPY --from=skmendez/static-ccextractor /ccextractor /usr/local/bin
`

### Copying from existing docker image - With OCR support (static link)
https://hub.docker.com/r/gizmotronic/ccextractor/dockerfile
`
COPY --from=gizmotronic/ccextractor /tmp/cc/ccextractor/linux/ccextractor /usr/local/bin/
COPY --from=gizmotronic/ccextractor /usr/local/share/tessdata /usr/local/share/tessdata
COPY --from=gizmotronic/ccextractor /tmp/cc/eng.traineddata /usr/local/share/tessdata
`

### Build example (dynamic link)
https://github.com/GrahamDigital/ccextractor-alpine/blob/master/Dockerfile
`
FROM alpine:3.8
LABEL maintainer="adam@grahamdigital.com"

RUN apk update; \
	apk upgrade; \
	apk add --update wget bash build-base tesseract-ocr-dev; \
	rm -rf /var/cache/apk/*

WORKDIR /opt/
RUN wget -O master.zip https://codeload.github.com/CCExtractor/ccextractor/zip/master; \
	unzip master.zip 'ccextractor-master/linux/*' -d /opt/; \
	unzip master.zip 'ccextractor-master/src/*' -d /opt/; \
	cd /opt/ccextractor-master/linux/; ./build; \
	cp ccextractor /usr/local/bin; \
	rm -rf /opt/*
`

**Comment by tobbenb** [comment]
I'm wondering why this is needed in tvheadend?
Recordings already have the subtitles and most players can use the subtitles.

**Comment by jefflessard** [comment]
I transcode recordings in mp4 using a post processing script. Source recordings are in mpegts format and includes in-stream EIA Closed Captions.

Unfortunately, ffmpeg doesn't manage those close captions pretty well. I have to first extract those closed captions using cc extractor prior to transcoding, in which I create a dedicated subtitle stream.

**Comment by tobbenb** [comment]
You can try to record in mkv format. Then the subtitles will be remuxed by tvheadend to its own stream as far as I know. You can also make profiles in tvheadend to transcode into another format to record directly.
It seems you know how to build ccextractor, and since this is a very niche thing I think it's better if you add those binaries yourself. If they are static you can just add it in your /config volume mount and point the script to the right path. Or you can use our built in mod support which is explained on our blog.
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by homerr** [comment]
Going to close this off, if there is a large demand for it in the future we could look to revisit it, but given @tobbenb suggestion on how to bake it in I think this is enough for now.
