### ISSUE TITLE
Request - Translate EPG

### ISSUE THREAD

**Issue by Chris230291** [linuxserver/docker-tvheadend#149]
Hello. Is it possible to translate the EPG data?
Or maybe grab new data in the users language using the original as a search term on imdb etc?
No idea how possible or how much work this would be.
Just a simple translate would be better than nothing.
From what I understand there already exists cmdline utilities that can translate text, but a built in polished version would be nicer.

Thanks for your time.

**Comment by tobbenb** [comment]
I don't see that this is something that this container should do. We are just packaging software into containers. Adding a translator is not something I think should be included.
This is better asked to the xmltv guys or your epg provider.

**Comment by Chris230291** [comment]
> I don't see that this is something that this container should do. We are just packaging software into containers. Adding a translator is not something I think should be included.
> This is better asked to the xmltv guys or your epg provider.

I use over the air EPG data. I dont use any of that xmltv rubbish. You guys added comskip and I thought this would work along the same lines.

Never mind.

**Comment by tobbenb** [comment]
Xmltv rubbish? Have you tried it? You might even get epg in your language using xmltv.
Translating over the air epg needs to be done by tvheadend as epg is stored in a database periodically. Until its stored it's probably in memory.
Probably better to make a feature request to tvheadend about translation.

**Comment by Chris230291** [comment]
> Xmltv rubbish? Have you tried it? You might even get epg in your language using xmltv.
> Translating over the air epg needs to be done by tvheadend as epg is stored in a database periodically. Until its stored it's probably in memory.
> Probably better to make a feature request to tvheadend about translation.

Perhaps its just my setup but I didnt get on with it.
Firstly it didnt automatically map epg data to channels in most cases.
Then when it did it treated eg, Dicsovery (UK) Discovery (DE) Discovery (ES) Discovery (PL) as the same channel, because they have the same name. They are not the same.
Seems like using xmltv requires a lot a manual setup. When you connect to many satellites, this is very tedious.

**Comment by tobbenb** [comment]
The name of the channel and epg data channel name must match if tvheadend is to automatically match.
There is some work setting it up, but it's a one time thing.

**Comment by Chris230291** [comment]
A bit off topic now, but why cant TVH use service ID's?
eg rytec uses this to define channels on enigma
`<!-- 13.0E --><channel id="NASA.us">1:0:1:1F8:384:13E:820000:0:0:0:</channel><!-- NASA -->`

**Comment by tobbenb** [comment]
No idea if it's possible. That's something you need to ask the tvheadend devs about.
