### ISSUE TITLE
JSON XS appears to be missing from tvheadend latest

### ISSUE THREAD

**Issue by zaphod24** [linuxserver/docker-tvheadend#156]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

Seeing this in system logs:

WARNING: Perl module JSON::XS not installed.  JSON encode/decode performance will be poor.
------------------------------

## Expected Behavior

JSON::XS included
## Current Behavior

JSON::XS not included, tv_grab_zz_sdjson_sqlite takes 45+ minutes
## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by tobbenb** [comment]
I'll have a look at it and add the missing module. Thanks for reporting it.

**Comment by zaphod24** [comment]
Thank you! From the release notes. it was included at some point in the past.

**Comment by tobbenb** [comment]
Just had a look and it should be included. So not sure what is happening.
I'll post a test build you can try later.

**Comment by tobbenb** [comment]
Please test if it works using this as the repository

**Comment by zaphod24** [comment]
Thanks for the quick response! I'm quite new to docker, so what is the best way for me to pull the update and replace my existing tvheadend docker image with it? I followed the instructions at https://hub.docker.com/r/linuxserver/tvheadend/

**Comment by zaphod24** [comment]
I managed to muddle my way through, still get:

WARNING: Perl module JSON::XS not installed.  JSON encode/decode performance will be poor.

**Comment by zaphod24** [comment]
I managed to muddle my way through fetching the test image and re-creating my tvheadend container. The issue appears to be solved and the EPG fetch ran in 5ish minutes instead of 45. Hooray!

**Comment by tobbenb** [comment]
Thanks for testing. I'll clean up the PR and then it will be merged and built. 
Remember to change back to the normal repo so you get the update.

**Comment by zaphod24** [comment]
Thank you! I already updated to the latest regular repo build and all is well
