### ISSUE TITLE
Please Add an Friendly to use Filegrabber

### ISSUE THREAD

**Issue by DeBaschdi** [linuxserver/docker-tvheadend#158]
Hi, all the Filegrabbers for xml epg you ship with will import all .xml files inside tvheadend/data, this is not really a nice solution. please add this filegrabber :

https://github.com/b-jesch/tv_grab_file

This allows to choose an single .xml directly.
Thx

**Comment by DeBaschdi** [comment]
Hey guys, are there any problems?

**Comment by j0nnymoe** [comment]
We don't add anything custom to the TVHeadend install itself. We only take the EPG Grabbers from upstream so I would suggest seeing if it can be added there. Otherwise you could add it yourself by doing this: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
