### ISSUE TITLE
Clarification on SAT>IP net=host requirement

### ISSUE THREAD

**Issue by Ageraluon** [linuxserver/docker-tvheadend#162]
I am currently trying to access a DVB-C-Stream of my fritz box with tvheadend running as your docker container. However, the muxes fail with the message "no data". Currently I am trying to isolate the cause.

Hence the request for clarification: In the section "Host vs. bridge" you describe to use net=host when using IPTV, SAT>IP, etc. Do you also need to do this and does tvheadend also need the bradcast address if you are just trying to access the stream of a different unit broadcasting via SAT>IP?

Thank you and best regards

**Comment by tobbenb** [comment]
Sorry for the late reply.

You need to use host network if you want to use a stream from a SAT>IP source. It's caused by using multicast and the docker network not playing nice with multicast.

**Comment by Ageraluon** [comment]
Got it, thank you for the explanation!
