### ISSUE TITLE
XMLTV file grabber

### ISSUE THREAD

**Issue by Chris230291** [linuxserver/docker-tvheadend#164]
Would it be possible to have your file grabber import/merge multiple sources please? Maybe using tv_merge/tv_sort?

**Comment by tobbenb** [comment]
Not so keen on adding grabbers that are not in the xmltv package. You can use the option to customize our containers and add it yourself. There is a blog post about it at blog.linuxserver.io

**Comment by Chris230291** [comment]
Looks good. Thanks
