### ISSUE TITLE
xmltv.sock: chmod after  spinup

### ISSUE THREAD

**Issue by bolzerrr** [linuxserver/docker-tvheadend#165]
## Expected Behavior
After the container has started execute "chmod 666 epggrab/xmltv.sock"
This enables epggrabber from other containers to write to the socket

## Current Behavior
Need to be done manually

**Comment by tobbenb** [comment]
You automate this yourself using our option to customize our containers.
Check out https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by bolzerrr** [comment]
Thank you for the hint, i will give it a try. I was thinking it could be something that is interesting for all users.
