### ISSUE TITLE
Add Streamlink

### ISSUE THREAD

**Issue by Sparticuz** [linuxserver/docker-tvheadend#168]
Please add streamlink https://streamlink.github.io/ to this image.

It's currently in edge/testing in Alpine https://pkgs.alpinelinux.org/packages?name=streamlink, so not sure if it's easy to add, or just wait till it goes into a branch? (or manually install)

**Comment by Sparticuz** [comment]
As a note, I had to install py3-isodate from edge/community, then streamlink from edge/testing. I was able to successfully get it working.

**Comment by tobbenb** [comment]
This will not be added to the container. You can add it easily yourself by using this guide https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
That way it survives container updates.

**Comment by Chris230291** [comment]
Hello. Could someone please explain how I can add streamlink please? I know about `custom-cont-init.d` but alpine doesn't appear to have a streamlink package. I tried using the appimage method explained on the streamlink git page but I couldn't get it installed.

Thanks,
Chris

**Comment by Sparticuz** [comment]
You need to enable to edge testing repos in Alpine to install streamlink. An easier solution would be to just install via python-pip. See this script: https://github.com/cgomesu/tvhlink/blob/master/tools/docker/streamlink_for_tvh_container.sh

> Hello. Could someone please explain how I can add streamlink please? I know about `custom-cont-init.d` but alpine doesn't appear to have a streamlink package. I tried using the appimage method explained on the streamlink git page but I couldn't get it installed.
> 
> Thanks,
> Chris

**Comment by Chris230291** [comment]
perfect thanks
