### ISSUE TITLE
Setting timezone inside container

### ISSUE THREAD

**Issue by barzog** [linuxserver/docker-tvheadend#171]
As stated in docs https://hub.docker.com/r/linuxserver/tvheadend I create container with following options:
docker create --name=tvheadend -e PUID=65534 -e PGID=65534 -**e TZ=Europe/Minsk** --net=host -v /opt/docker/tvheadend/config:/config -v /media/Transcend/torrent/recordings/:/recordings -v /media/Transcend/torrent/timeshift/:/timeshift --restart always linuxserver/tvheadend

Checking TZ variable using 'set | grep TZ' command inside container shows that TZ is correctly set to Europe/Minsk.
But `date` output inside container shows 
Fri Nov 20 13:13:22  2020 
and it is definitely UTC (localtime is 16:13).

When I put TZ=EET instead of Europe/Minsk then `date` output shows Fri Nov 20 13:13:22 EET 2020 - UTC again, but timezone is displayed.

In docker -f logs UTC also
2020-11-20 13:13:27.006 [   INFO] spawn: Executing "/usr/bin/tv_grab_wg"

this affects DVR/TV Guide functionality.

**Comment by aptalca** [comment]
What's the host OS?

**Comment by barzog** [comment]
armv7l on raspberry pi. host system - alpine

**Comment by aptalca** [comment]
upstream issue, see here: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12057#note_124235

**Comment by barzog** [comment]
But in host system, which is alpine too - all working perfectly (through /etc/localtime).
Here is date output from host system:
rp1:~# date
Fri Nov 20 16:38:47 +03 2020
rp1:~#
Is there any 'workaround'? 
I've tried to mount -v /etc/timezone/Europe/Minsk:/etc/localtime with no luck.

**Comment by barzog** [comment]
Workaround is to create container with following:
docker create --name=tvheadend -e PUID=65534 -e PGID=65534 **-e TZ='-3'** --net=host -v /opt/docker/tvheadend/config:/config -v /media/Transcend/torrent/recordings
/:/recordings -v /media/Transcend/torrent/timeshift/:/timeshift --restart always linuxserver/tvheadend

(why it is -3 it is still not clear, because EET is +3). 
rp1:~# docker exec -it tvheadend /bin/bash
root@rp1:/# date
Tue Nov 24 13:59:52  2020

2020-11-24 14:00:35.878 [   INFO] main: Log started

But now in tvheadend I see following
2020-11-24 14:00:36.248 [   INFO] spawn: Executing "/usr/bin/tv_find_grabbers"
2020-11-24 14:00:39.824 [  ERROR] spawn: ERROR: Date::Manip unable to determine Time Zone.  GMT will be used.
2020-11-24 14:00:39.915 [  ERROR] spawn: ERROR: Date::Manip unable to determine Time Zone.  GMT will be used.

**Comment by barzog** [comment]
After latest commit bd0e418 - all working perfectly.

rp1:~# docker create --name=tvheadend -e PUID=65534 -e PGID=65534 -e TZ=Europe/Minsk --net=host -v /opt/docker/tvheadend/config:/config -v /media/Transcend/torrent/recordings/:/recordings -v /media/Transcend
/torrent/timeshift/:/timeshift --restart always linuxserver/tvheadend

2020-12-05 20:05:16.086 [ NOTICE] START: HTS Tvheadend version 4.3-1916~g1884300f0 started, running as PID:282 UID:65534 GID:65534, CWD:/run/s6/services/tvheadend CNF:/config
rp1:~# docker exec -it tvheadend /bin/bash
root@rp1:/# date
Sat Dec  5 20:07:22 +03 2020
root@rp1:/#
