### ISSUE TITLE
add libxml2 to ffmpeg

### ISSUE THREAD

**Issue by hwahlis** [linuxserver/docker-tvheadend#174]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Use DASH manifests "mpd" as input ffmpeg (--enable-libxml2)

## Current Behavior

when testing this i get this output "Invalid data found when processing input"
## Alternatives Considered

When installing ffmpeg the usual way its included

**Comment by hwahlis** [comment]
I dont know if this is the right way to request this its my first time doing this

**Comment by tobbenb** [comment]
We just install ffmpeg from the alpine repo, so if it's not included in ffmpeg there isn't anything we can do.
