### ISSUE TITLE
Services 'Parent Disabled'

### ISSUE THREAD

**Issue by burny0202** [linuxserver/docker-tvheadend#177]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Services should be easily found. None should be 'Parent Disabled' which stops them being mapped to channels

## Current Behavior

Many services are not found, when searching muxes and those which show are largely assigned to 'Parent disabled' and unable to be mapped.

Configuration of the TV Adapters match those in the 4.2 stable (Your docker image). Adjusting PID Max does not make any significant difference. Seems to be random.

Network is enabled.

Probably related - EPG OTA takes forever with large gaps

Tried raising with TVHeadEnd, which said to raise here.

Screenshots of current vs 4.2

![image](https://user-images.githubusercontent.com/37351981/117049765-7e977500-ad0c-11eb-9f23-e21638e24138.png)
![image](https://user-images.githubusercontent.com/37351981/117049820-9111ae80-ad0c-11eb-88f0-18cb9caf65f3.png)
![image](https://user-images.githubusercontent.com/37351981/117049943-b3a3c780-ad0c-11eb-8ff2-c88c137a8911.png)
![image](https://user-images.githubusercontent.com/37351981/117050023-c918f180-ad0c-11eb-8f92-2afb0f44026f.png)

## Steps to Reproduce

1. Create Docker
2. Create Network
3. Enable & Assign all DVB-T tuners to the network
4. Force Scan Muxes
5.  Limited services found. Most 'Parent Disabled'

## Environment
**OS:**Ubuntu Server. 20
**CPU architecture:** x86_64
**How docker service was installed:** Docker from official repo

## Command used to create docker container (run/create/compose/screenshot)

sudo docker run -d --restart unless-stopped --name=tvheadend -e PUID=111 -e PGID=44 -e TZ=Europe/London -p 9981:9981 -p 9982:9982 -v /srv/tvheadend/config:/config -v /NAS/Media/TV:/recordings --device /dev/dvb:/dev/dvb 

## Docker logs

N/A

**Comment by burny0202** [comment]
Updated with template.

**Comment by j0nnymoe** [comment]
Just to clarify, 4.2 is the one with the issue and not what's in current?

**Comment by burny0202** [comment]
> Just to clarify, 4.2 is the one with the issue (on the left of the screenshots) and not latest?

Issue is with the current

**Comment by j0nnymoe** [comment]
> > Just to clarify, 4.2 is the one with the issue (on the left of the screenshots) and not latest?
> 
> Issue is with the current (latest)

I would suggest reporting this issue to TVHeadend directly as we only build/package what's currently in their master branch. If they then point out it is indeed an issue with our container, it can be looked at.

**Comment by burny0202** [comment]
The issue is replicated in my direct build of TVHeadend. It has been raised with them; though unlikely to be fixed

**Comment by j0nnymoe** [comment]
Ok, Thank you for letting us know. Closing this issue as it's a TVH bug and not container related.
