### ISSUE TITLE
Support iHD / intel-media-server Driver for VAAPI

### ISSUE THREAD

**Issue by rado0x54** [linuxserver/docker-tvheadend#178]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Hardware encoding via VAAPI does not work with the i985 (libva-intel-driver) driver and newer GEN hardware. Please also provide iHD (intel-media-driver) within the Docker image.

------------------------------

## Expected Behavior

`vainfo` works on newer Intel Hardware.

## Current Behavior

`vainfo` does not work and returns:
```
root@f41ec8fafcce:/# vainfo 
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva error: /usr/lib/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

## Steps to Reproduce

1. `bash` into container
2. echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
3. apk update
4. apk add libva-utils@testing
5. run `vainfo`

## Environment
**OS:**
**CPU architecture:** x86_64
**How docker service was installed:**

snap

## Command used to create docker container (run/create/compose/screenshot)

docker-compose (standard from example)

## Docker logs

N/A

## Fix:
Installing `intel-media-driver` fixes the problem and `vainfo` works and `ffmpeg` transcoding with a vaapi encoder works.

**Comment by tobbenb** [comment]
This is better suited as a docker mod. I'm not so fond of using edge repos.

**Comment by rado0x54** [comment]
Yes correct. I only used the edge repo for testing with vainfo.
