### ISSUE TITLE
docker run command

### ISSUE THREAD

**Issue by koendv** [linuxserver/docker-tvheadend#185]
Thanks for this docker image. Just a small note: if you use a sat-ip server on the local network, in the ``docker run`` replace
``
docker run -d 
  -p 9981:9981 
  -p 9982:9982 
...
``
with
``
docker run -d 
--net=host  
...
``

**Comment by j0nnymoe** [comment]
This is already stated in the readme https://github.com/linuxserver/docker-tvheadend#host-vs-bridge .
