### ISSUE TITLE
Broken i915 driver on Intel Geminilake (Gen9) when Added Intel iHD driver support.

### ISSUE THREAD

**Issue by psycmos** [linuxserver/docker-tvheadend#186]
Since 
"11.05.21: - Added Intel iHD driver support" 
the driver of  Intel Geminilake (Gen9) ( i915) stops working.
To get it working, we need to remove that driver from docker.

For Example:
mv /usr/lib/dri/iHD_drv_video.so /usr/lib/dri/iHD_drv_video.so.disabled

I saw the issue in Emby users forum:
As of Emby 4.6.* which includes an iHD driver with fixes for Gemini Lake it's no longer necessary to disable iHD.

Maybe it helps to find the issue.

**Comment by DOFfactory** [comment]
I am reporting that with the latest version update to tvheadend (HTS Tvheadend 4.3-1983~gb8710206e), linuxserver/tvheadend: b8710206-ls115 the whole intel iHD and i965/i915 is broken. No video transcoding whatsoever. Please provide a fix.
