### ISSUE TITLE
Issue with XMLTV/TV_GRAB after ALPINE 3.15 rebase

### ISSUE THREAD

**Issue by madasus** [linuxserver/docker-tvheadend#188]
No issue on IMAGE: 09a2c71a-ls116 (rolled back to confirm)
Issue exists on IMAGE: 3ed76138-ls117 (and still exists on c7b713ed-ls118)

Running docker on a Synology NAS (as I have for years).  XMLTV appears to be unable to write out to the cache file and this causes the system to not be able to update the guide in TVH.  I have tried moving the cache files to docker storage vs mapped storage but the problem remains and also tried deleting the files and letting the system re-create.

Log shows initial error

root@1ca6515061af:/config/xmltv# tv_grab_zz_sdjson --config-file tv_grab_sd_json_2.conf --days 1 --debug
Initializing...
Magic number checking on storable file failed at /usr/lib/perl5/core_perl/Storable.pm line 421, at /usr/bin/tv_grab_zz_sdjson line 693.

Then processes lots of data and ends with

** POST https://json.schedulesdirect.org/xxxxxxx/schedules ==> 200 OK (11s)
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/bin/tv_grab_zz_sdjson line 278.

Happy to share any more information.  For now I rolled back to the image before the rebase and the same XML file works fine.

**Comment by UtopiaOpera** [comment]
> Still broken in the latest release

Would this be the issue I'm seeing too?
The EPG data comes in, and then a few minutes later, sporadically disappears leaving cavities in the EPG data, before eventually disappearing all together.

**Comment by madasus** [comment]
I have no issue on 09a2c71a-ls116 - so likely your problem is different.

If you execute into the docker and run the epg grab manually and see if you are getting errors.

**Comment by UtopiaOpera** [comment]
> I have no issue on 09a2c71a-ls116 - so likely your problem is different.
> 
> If you execute into the docker and run the epg grab manually and see if you are getting errors.

Gottcha.
I notice the aforementioned image only had the issue with some channels after letting the EPG sit, channels with EPG issues seem to be on the same mux.
I'm coming here from a standard repo install on the RPi (which is ver: 4.2.8-34~g24a2f59e9) and now learning / moving over, to Docker. 
The Tvheadend version in these Docker images is newer to the RPi repo version.
Boring story short, I had to edit the Mux and manually select the EPG module ID setting it to UK: Freeview in my case. Seems to have fixed it for that mux. 
The EPG module select option isn't there in the Pi repo install, BUT, I never had this mux EPG issue with that version either.
I might log this as a separate issue.

Cheers.

**Comment by joeczucha** [comment]
Experiencing the same on a Synology NAS. Reported it to https://github.com/XMLTV/xmltv/issues/169 as I didn't realise it was specific to the docker image, but perhaps the response dump will shed some light: 

    x-died' => 'read failed: Invalid argument at /usr/share/perl5/vendor_perl/LWP/Protocol/[http.pm](http://http.pm/) line 471.',

**Comment by Gronda74** [comment]
This still appears broken in the latest release. As with @madasus it all works fine on 09a2c71a-ls116 but each release after that has the same issue for me.

**Comment by joeczucha** [comment]
Did anyone ever find a workaround for this?

**Comment by Gronda74** [comment]
Not so far. I'm still running 09a2c71a-ls116 .

**Comment by Gronda74** [comment]
Had hoped that the latest version (https://github.com/linuxserver/docker-tvheadend/releases/tag/fbc94aee-ls129) would resolve this but having just updated my test environment to it, it's still not working.

**Comment by Gronda74** [comment]
Updated my test setup to 1c65e8b0-ls133 last night. Still no change on this front though.

**Comment by Gronda74** [comment]
Updated my test setup to 1c65e8b0-ls136. Still no change on this front. Looks like this is now just broken for good.

**Comment by Gronda74** [comment]
Updated my test setup to 4741b3c1-ls141 yesterday, this remains broken.

**Comment by Gronda74** [comment]
This is still not working.

**Comment by joeczucha** [comment]
Still not working

**Comment by Gronda74** [comment]
Still not fixed as of version e2ae8f4e-ls121

**Comment by Gronda74** [comment]
I'm still using image 09a2c71a-ls116 as this remains unfixed since the changes after that image.

**Comment by Gronda74** [comment]
Just updated to 470f02fb-ls150. Still not working.

**Comment by j0nnymoe** [comment]
Could someone test this build please? lspipepr/tvheadend:44bf691a-pkg-cdeb2d7f-pr-218

**Comment by Gronda74** [comment]
Yes, just spun this up with my test setup and it looks like it's fixed this. Fantastic, thank you!

**Comment by j0nnymoe** [comment]
@Gronda74 perfect, thanks for testing, I'll get that merged in the image.

**Comment by j0nnymoe** [comment]
Infact it's already merged.
