### ISSUE TITLE
TVHeadend Container is not starting - libseccomp

### ISSUE THREAD

**Issue by MartinBachmannHD** [linuxserver/docker-tvheadend#189]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
TVHeadend container should start from Portainer / Docker

## Current Behavior
Since a few minor releases the TVHeadend container is not working any more, it looks like a libseccomp issue to me - this is listed in the log. Here a few recommended actions are listed, but none of these are possible (no dpkg or sudo inside the container...). 
So I cannot use the WebPage (...;9981) any more, the service is not starting.
The container was working correctly a few weeks ago, so this image is working fine: linuxserver/tvheadend:b8710206-ls115

## Steps to Reproduce

1. apt-get update and apt-get upgrade on RPi, then use the latest version via docker-compose (c7b713ed-ls118) on Docker on RaspberryPi
2. start the TVHeadend container
3. check if the WebUi (...:9981) is available, check docker logs

## Environment
**OS:** linux, Raspbian GNU/Linux 10 (buster)
**CPU architecture:** armv7l
**Docker Server Version: 20.10.12
**How docker service was installed:**
Installation via the docker compose script listed here: https://github.com/linuxserver/docker-tvheadend. 
In addition to lscr.io/linuxserver/tvheadend I also used this repo: docker.io/linuxserver/tvheadend:latest

## Command used to create docker container (run/create/compose/screenshot)
---
version: "2.1"
services:
  tvheadend:
    image: docker.io/linuxserver/tvheadend:latest
    container_name: tvheadend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      
    volumes:
      - /media/pi/usb1285/TVConfig:/config
      - /media/pi/usb1285/TVRec:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    restart: unless-stopped

## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Your DockerHost is running an outdated version of libseccomp
To fix this, please visit https://docs.linuxserver.io/faq#libseccomp
Apps will not behave correctly without this

**Comment by Roxedus** [comment]
None of the fixes at https://docs.linuxserver.io/faq#libseccomp is to be done in the container, you need to fix your host.

**Comment by MartinBachmannHD** [comment]
Thanks - that fixed it! I was under the impression that apt-get upgrade would do everything, and no manual action from me would be required....
Again -thaks a lot!
