### ISSUE TITLE
python: is missing in image

### ISSUE THREAD

**Issue by disaster123** [linuxserver/docker-tvheadend#190]
current latest master image:
```
2022-02-11 21:24:35.832 [   INFO] spawn: Executing "/usr/bin/tvhmeta"
2022-02-11 21:24:36.173 [  ERROR] spawn: env: ‘python’: No such file or directory
```

tvhmeta uses python env shebang line. But there is no python in env.

Greets,
Stefan

**Comment by tobbenb** [comment]
Please fill in the template correctly.

Python is installed in the image.

https://github.com/linuxserver/docker-tvheadend/blob/5c95e3cd543617d529de8526701f363f1ec0fad0/Dockerfile#L312

**Comment by disaster123** [comment]
> Please fill in the template correctly.
> 
> Python is installed in the image.
> 
> https://github.com/linuxserver/docker-tvheadend/blob/5c95e3cd543617d529de8526701f363f1ec0fad0/Dockerfile#L312

Yes python is installed but only available as python3 not python:

See here:
```
root@tvheadend:~# docker exec -it tvheadend bash
root@09e5395ec776:/# python3
python3    python3.9  
root@09e5395ec776:/# python3
python3    python3.9  
root@09e5395ec776:/# python3^C
root@09e5395ec776:/# which python
root@09e5395ec776:/# which python3
/usr/bin/python3
root@09e5395ec776:/# ls -la /bin/py*
ls: cannot access '/bin/py*': No such file or directory
root@09e5395ec776:/# ls -la /usr/bin/py*
lrwxrwxrwx 1 root root     8 Feb  6 16:17 /usr/bin/pydoc3 -> pydoc3.9
-rwxr-xr-x 1 root root    78 Nov 24 22:15 /usr/bin/pydoc3.9
lrwxrwxrwx 1 root root     9 Feb  6 16:17 /usr/bin/python3 -> python3.9
-rwxr-xr-x 1 root root 13976 Nov 24 22:15 /usr/bin/python3.9
root@09e5395ec776:/# head -n1 /usr/bin/tvhmeta
#! /usr/bin/env python
root@09e5395ec776:/# env python
env: ‘python’: No such file or directory
root@09e5395ec776:/# 

```

**Comment by tobbenb** [comment]
It's because alpine use python for python 2. 
Can you try to make a link from pythone to python and see if it works then?

**Comment by disaster123** [comment]
@tobbenb this is now fixed upstream by using python3 instead of python. We just need new  docker images ;-)

**Comment by tobbenb** [comment]
Good thing they stopped using python 2 as it was EOL 2 years ago.

We stopped building the master branch of tvheadend as the build fails too much and sends our builders in a loop.
It would be great if tvheadend would at least do some pre releases.

**Comment by disaster123** [comment]
@tobbenb so we need a new docker image / hub?

**Comment by j0nnymoe** [comment]
What we need is TVHeadend not to be failing to build at master and for at least them to start cutting working (pre)releases again.

**Comment by disaster123** [comment]
I truly inderstand but then please do not close this issue as it is present until a rebuilded image is available.
