### ISSUE TITLE
Sometimes I have to restart the container for IPTV to work again.

### ISSUE THREAD

**Issue by Chris230291** [linuxserver/docker-tvheadend#202]
After some time I start getting `tvhpoll: epoll` errors when I try to play a IPTV stream (I have AV library enabled).
Restarting the container always fixes it and streams play perfectly.
Could this be some kind of memory issue or docker limitation?
There are no steps to reproduce... It just starts happening after a while.
When I am having this issue all other networks (dvb-s, dvb-t) still work perfectly.
Any ideas?

**Comment by j0nnymoe** [comment]
This is a question that would be better asked for tvheadend themselves.

**Comment by Chris230291** [comment]
> This is a question that would be better asked for tvheadend themselves.

If restarting the container fixes the issue, then is it not a container/docker issue?

**Comment by j0nnymoe** [comment]
If it falt out didn't work, then sure. But I would assume it's bug in their code considering dvb doesn't have the same issue.
