### ISSUE TITLE
Nvidia NVENC support

### ISSUE THREAD

**Issue by teminvictus** [linuxserver/docker-tvheadend#207]
Can you add Nvidia NVENC support?
Compatible to the [Nvidia Docker Toolkit](https://github.com/NVIDIA/nvidia-docker).

thanks

**Comment by aptalca** [comment]
Iirc ffmpeg already supports nvenc. You just need to install nvidia-docker on your host and enable gpu support for the docker service

**Comment by aptalca** [comment]
Are you sure? Last I looked at it (a few years back), ffmpeg didn't need any external libraries for nvenc build time, so pretty much all ffmpeg builds had nvenc support enabled (there was no reason not to).

**Comment by aptalca** [comment]
Sorry, I have been corrected in our discord

Nvidia toolkit or nvidia-docker (or whatever nvidia is calling it these days) is dependent on glibc, but alpine (the OS in our tvheadend image) uses muslc and therefore they are not compatible.
