### ISSUE TITLE
Picons not loading (permissions issue?)

### ISSUE THREAD

**Issue by Morphy99** [linuxserver/docker-tvheadend#210]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Picons should load in Kodi and TVH client for Android

## Current Behavior
Currently not getting any channel icons loading which I think is due to a permissions issue:
```
root@dda1e42d913e:/picons# ls -la bbconehd.png
---------- 42 nobody abc 5642 Nov  9 16:41 bbconehd.png
```

## Steps to Reproduce
Set TVH Settings:
![image](https://user-images.githubusercontent.com/5853979/202818711-720a774f-892b-4d98-8046-275cad1e0eff.png)
![image](https://user-images.githubusercontent.com/5853979/202818756-8f54e75b-6d5d-4183-87a8-3ada1a70707b.png)

I get lots of `HTTP/1.1 HEAD (2) /imagecache/5098 -- 404` errors in the logs

## Environment
**OS:** Libreelec
**CPU architecture:** x86_64
**How docker service was installed:** LE addon

**Comment by j0nnymoe** [comment]
The settings should be:

```

    Picon

    Channel icon path: file:///picons/%C.png

    Channel icon name scheme: Service name picons

    Picon path: BLANK

    Picon name scheme: Standard
```
Note the extra /

**Comment by Morphy99** [comment]
Thanks for the reply. I tried the settings as you mentioned: 
![image](https://user-images.githubusercontent.com/5853979/203512169-b7e63b6f-f7b4-4108-a3a9-9172c913f163.png)

Still no dice. The settings for %c and name scheme seem to be correct from what I can see, but that doesn't work either.

The fle exists: 
![image](https://user-images.githubusercontent.com/5853979/203513035-0dba0e88-9aec-4f70-ac38-7d8364216b85.png)

The channel is set correctly:
![image](https://user-images.githubusercontent.com/5853979/203513289-643076e6-7076-45e6-8755-af706834bd9e.png)

**Comment by Morphy99** [comment]
So I've got it working. I ditched the LE LSIO addon and just did a docker compose. Set these env variables:
```
  -e PUID=0 \
  -e PGID=0 \
```
Set the Channel icon path to `file:///picons/%U.png`
Disabled image cache too.
