### ISSUE TITLE
RUN_OPTS doesnt work

### ISSUE THREAD

**Issue by gdomod** [linuxserver/docker-tvheadend#211]
i have try many parameters but nothing works, i got a restart loop.
i checked RUN_OPTS enviroment, thats correct.

try yourself with
`environment:
      - RUN_OPTS=--debug`

**Comment by jarondl** [comment]
Maybe this is related to #204 (by @aptalca).
Anyway, I ran `docker exec tvheadend /bin/bash`, and inside it `echo $RUN_OPTS`. It printed out `"--http_root /tv"`. Notice the quotes! What worked for me as a workaround was quoting the whole environment variable. Replacing:
```
environment:
  - RUN_OPTS=--http_root /tv
```
With:
```
environment:
  - "RUN_OPTS=--http_root /tv"
```

And everything worked.

Either the code needs to be fixed, or the docs updated to include these quotes.

**Comment by jarondl** [comment]
This is not stale.

**Comment by j0nnymoe** [comment]
I don't see why this is still open, you figured out you need to wrap the env in " like you provided above.
