### ISSUE TITLE
[FEAT] Nvidia Encoding Support

### ISSUE THREAD

**Issue by BenSchweikert** [linuxserver/docker-tvheadend#215]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Additional Docker Image with enabled Nvidia HW encoding and decoding support based (as far as possible) on the existing Dockerfile.
The "proposed code change" is my working Dockerfile. I just wanted to share my work in case some one else is looking for Nvidia support.

### Reason for change

Encoding and Decoding support to reduce CPU load and use GPU instead.

### Proposed code change

see attachment.
[Dockerfile.txt](https://github.com/linuxserver/docker-tvheadend/files/10473148/Dockerfile.txt)

**Comment by j0nnymoe** [comment]
Not possible while the image is based on alpine.
