### ISSUE TITLE
[FEAT] Add back armv7 support

### ISSUE THREAD

**Issue by dontobi** [linuxserver/docker-tvheadend#223]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I have been using this Docker container on my Raspberry pi for a long time. Unfortunately I found out that ARMv7 support has been discontinued. If I see it correctly, this is due to the change to Alpine 3.17 and a build error.

What is wrong with offering an ARMv7 build with Alpine 3.15?

If you ask why I don't use ARM64 on my Raspberry Pi: I use a Raspberry Pi 3 which doesn't support ARM64.

### Reason for change

An ARMv7 build has been offered so far.

**Comment by aptalca** [comment]
https://info.linuxserver.io/issues/2023-02-25-tvheadend/
https://www.linuxserver.io/blog/a-farewell-to-arm-hf
https://www.linuxserver.io/blog/end-of-an-arch

**Comment by dontobi** [comment]
Okay. I will switch on the ARM64 support. But if I get Userland converted to 64bit is questionable. Unfortunately, reinstalling is currently not possible without further ado.
