### ISSUE TITLE
[FEAT] enable libxml2

### ISSUE THREAD

**Issue by fatshotty** [linuxserver/docker-tvheadend#225]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi, is it possible to add libxml2 to tvheadend image?
Maybe ffmpeg needs the `--enable-libxml2` option

### Reason for change

it could be nice to make tvheadend manage `.mpd` link url via ffmpeg piping

**Comment by fatshotty** [comment]
thanks for quick reply
Other question:
is it possibile to try compile ffmpeg with --enable-libxml2 ? Or is there a way to use an external ffmpeg with --enable-libxml2  flag?

**Comment by thespad** [comment]
You'd have to find a version built against muslc for it to work on Alpine. You could also raise an issue against the Alpine package repos and request they add it, then we'd pull it in automatically - https://gitlab.alpinelinux.org/alpine/aports/-/issues

**Comment by fatshotty** [comment]
thanks for reply
I submitted the issue to gitlab

many thanks

**Comment by fatshotty** [comment]
here is the answer about ffmpeg:
https://gitlab.alpinelinux.org/alpine/aports/-/issues/14922#note_307003

**Comment by thespad** [comment]
> here is the answer about ffmpeg: [gitlab.alpinelinux.org/alpine/aports/-/issues/14922#note_307003](https://gitlab.alpinelinux.org/alpine/aports/-/issues/14922#note_307003)

Thanks, I'll add TVH to our list for higher priority 3.18 rebases so it can take advantage of the new ffmpeg build. Might be several weeks though.

**Comment by fatshotty** [comment]
hi, just another input, maybe can help:
https://github.com/jrottenberg/ffmpeg/issues/376

**Comment by fatshotty** [comment]
hi, any news about that?
