### ISSUE TITLE
[BUG] TV_grab_url permission

### ISSUE THREAD

**Issue by SmoothVirus** [linuxserver/docker-tvheadend#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the XMLTV: XMLTV URL grabber module the result of running /usr/bin//usr/bin/tv_grab_url is:
2023-10-14 21:46:01.001 spawn: Executing "/usr/bin/tv_grab_url"
2023-10-14 21:46:01.343 xmltv: /usr/bin/tv_grab_url: no output detected
2023-10-14 21:46:01.343 xmltv: /usr/bin/tv_grab_url: grab returned no data

In researching this it looks like it is a permission issue. The script is running under root and should run under user abc.  I came across the same issue with the sd pull and the files in .xmltv were created by root rather than abc. Once I chowned the files to abc the sd stuff worked.

### Expected Behavior

The script should run and pull down the content of the url.

### Steps To Reproduce

Enable  XMLTV: XMLTV URL in the TvHeadend EPG section and put a value url into the paramter box.

### Environment

```markdown
- OS: Linux c21a05027f6f 5.19.17-Unraid #2 SMP (slackware)
- How docker service was installed: (Via unraid)
```

### CPU architecture

x86-64

### Docker creation

```bash
used your default params from the unraid container.
```

### Container logs

```bash
not available.
```

**Comment by ziogref** [comment]
Looking at the permissions on the docker container, custom mapped EPG files get mapped as abc:abc where as everything else is owned by root:root

chmod +777 on the file on unraid is a bandaid fix allowing the container to execute the shell script in the container successfully adding the the TV GRAB file

**Comment by djkotik** [comment]
I am trying to add a custom epg grab file (https://i.mjh.nz/nz/tv_grab) and have accessed the dockers console, changed to the /usr/bin folder and used wget to download this file. I then used chmod +x and chmod +777 on the file however after restarting tvheadend it is still missing this epg grabber module. Previously this has worked but no longer seems to. I am not sure how else I can add this file or why it is not being discovered? 

HTS Tvheadend 4.3-2161~gbc30a74de
UNRAID Version 6.12.4 2023-08-31

**Comment by djkotik** [comment]
This is still an issue for me. I cannot get my guide to epg tv_grab file to load and be usable within tvheadend.
