### ISSUE TITLE
[FEAT] Allow for setting up username and password from docker-config

### ISSUE THREAD

**Issue by Lorthiz** [linuxserver/docker-tvheadend#244]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Can we have variable for setting root name and password? Or support for passwords for new accounts?

### Reason for change

There is a plugin for TvHeadEnd in Jellyfin that requires that Password is not empty otherwise plugin ends up "Malfunctioned"
I tried creating new user but I can't find a single place where to put password for that user. Right now it requires users to restart Jellyfin instance multiple times going to Dashboard -> Plugins -> TvHeadEnd -> three dots -> Settings -> find password field and change it

**Comment by j0nnymoe** [comment]
No plans to add this. Users can be setup by triggering the wizard or going to the users/password tab: http://docs.tvheadend.org/webui/config_passwords/
