### ISSUE TITLE
[BUG] Picons are out of date

### ISSUE THREAD

**Issue by jonjomckay** [linuxserver/docker-tvheadend#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to find some picons for channels that do have picons in the source repository, I'm unable to find them in the image.

For example, [`bbcradiocornwall.default.svg`](https://github.com/picons/picons/blob/master/build-source/logos/bbcradiocornwall.default.svg) exists in the picons source, but `bbcradiocornwall.png` does not exist in the latest Tvheadend Docker image.

### Expected Behavior

Picons that exist in the picons source repository are available in the Tvheadend Docker image.

### Steps To Reproduce

Assign `file:///picons/bbcradiocornwall.png` to a channel, and see that the file doesn't exist.

### Environment

```markdown
- OS: Arch Linux
- How docker service was installed: Docker Compose
```

### CPU architecture

x86-64

### Docker creation

```bash
tvheadend:
  image: lscr.io/linuxserver/tvheadend:version-583de233
  container_name: tvheadend
  network_mode: host
  environment:
    - PUID=1000
    - PGID=1002
    - TZ=Europe/London
  deploy:
    resources:
      limits:
        memory: 1536m
  volumes:
    - /var/local/tvheadend:/config
    - /media/download/recordings:/recordings
  restart: unless-stopped
```

### Container logs

```bash
2023-12-08 21:09:51.283 [  ERROR] http: 192.168.0.250: HTTP/1.1 GET (1) /imagecache/555 -- 404
2023-12-08 21:09:51.291 [  ERROR] http: 10.42.1.80: HTTP/1.1 GET (1) /imagecache/414 -- 404
2023-12-08 21:09:51.293 [  ERROR] http: 10.42.1.80: HTTP/1.1 GET (1) /imagecache/418 -- 404
2023-12-08 21:09:51.325 [  ERROR] http: 192.168.0.250: HTTP/1.1 GET (1) /imagecache/555 -- 404
2023-12-08 21:09:51.325 [  ERROR] http: 10.42.1.80: HTTP/1.1 GET (1) /imagecache/418 -- 404
2023-12-08 21:09:51.342 [  ERROR] http: 192.168.0.250: HTTP/1.1 GET (1) /imagecache/414 -- 404
```

**Comment by aptalca** [comment]
Picons are built and pushed weekly by this repo: https://github.com/linuxserver/picons-builder
And then each tvh build imports the latest picon build artifact.

If the picon was recently added to the source repo, it may be a couple of weeks for it to show up in tvh due to the waterfall effect of the builds.

**Comment by jonjomckay** [comment]
The icon was added to the source repository 8 months ago though.

If I've followed the trail successfully, [this CI build](https://ci.linuxserver.io/job/Docker-Pipeline-Builders/job/docker-tvheadend/job/piconbuild/) for the `picons-builder` repository doesn't look like it's been run in about the same amount of time.

**Comment by aptalca** [comment]
That jenkins job was deprecated. The repo I linked earlier builds them as a scheduled GitHub workflow

**Comment by jonjomckay** [comment]
Ah OK. The icon still isn't part of the image though. What do we need to do to solve this?

**Comment by aptalca** [comment]
Look through the repo I linked and see how the picons are generated. Maybe you'll notice an issue.

I'm not familiar with picons at all. The person who created the builder left the team a long time ago. I just moved the generator over from the the old Jenkins job to GitHub workflows. I didn't change the generation process.

**Comment by pvanerp** [comment]
I'm having the same issue, new channel icons are not appearing in tvheadend. I've had a look in the picon builder script and noticed there are differences in the script and the picons-readme, but I'm not sure if this is causing it to not update.

The prerequisites are listed in the readme but are missing
- binutils
- librsvg2-bin 
- jq

Furthermore
- git clone https://github.com/picons/picons doesn't have .git at the end
- copying background.conf is not mentioned in the readme
- the script calls ./2-build-picons.sh snp-full but the readme mentions calling ./1-build-servicelist.sh and ./2-build-picons.sh

**Comment by homerr** [comment]
I'll have a go at fixing it... no promises!

**Comment by homerr** [comment]
I've spent some time this morning looking into this, and unfortunately, the error isn't something we can resolve. I can see that our picon builder job is running as it should be, I can then see the icons in the container are as up-to-date as possible from these builds.

Taking your example of BBC Radio Cornwall, I can't find the icon in our image, nor does it generate when I manually create the picons (both in Docker as we do, and manually) but more so it is not generating the icon when using the default `backgrounds.conf` file that comes from the picon repository, which is all that we have customised. 

You may find some use in raising an issue with them and finding out why these icons do not generate. From what I can tell, the `1-build-servicelist.sh` script will generate a list of icons that should be generated, from existing sources you run (e.g. TVHeadend).

As this is a generic builder for all people, we build all icons. 

Sorry we cannot be any further help on this.
