### ISSUE TITLE
[FEAT] IPv6 Support 

### ISSUE THREAD

**Issue by simpz** [linuxserver/docker-tvheadend#246]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The container seems to support IPv6 (well the interfaces pick up an IPv6 addresses in the container) , but the application itself doesn't allow being connected to from IPv6. I also presume (though I don't really use this functionality) that outbound to the Internet from TVheadend will be IPv4.

Though I don't know if TVheadend itself supports IPv6, though I think it does.

### Reason for change

Future proofing and consistency with every other application.There is also the minor issue that in an IPv6 environment IPv6 is always tried first by clients and they have to drop back to IPv4, this is slight slow down.

**Comment by j0nnymoe** [comment]
IPv6 support isn't related to the container but rather to the setup of your docker install. Nothing should need to be added to the container for it to work (unless tvheadend doesn't support it).

**Comment by simpz** [comment]
The container (as I said) has an IPv6 address my setup is correct as I can ping it's IPv6 address from another container. 

Inside the container the tvheadend application is only listening on IPv4. I can run "nc -l6 -p 9123" inside the container and connect via IPv6 and see it's listening on IPv6.  See below

```
root@0e626be35385:/# netstat -apn
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:9982            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9981            0.0.0.0:*               LISTEN      -
tcp        0      0 10.89.1.4:9982          192.168.1.100:48210   ESTABLISHED -
tcp        0      0 10.89.1.4:9981          192.168.1.128:53736   ESTABLISHED -
tcp        0      0 :::9123                 :::*                    LISTEN      
```

**Comment by simpz** [comment]
Actually I've managed to make this work. I just had to pass a command line arg to the docker run to force tvheadend to listen on IPv6 in the container.
`-e RUN_OPTS='--ipv6' `

Will close and leave here in the hope this is useful to someone else.

Thanks for the attention.

**Comment by davidebeatrici** [comment]
According to https://tvheadend.org/d/5872-ipv6-accessing-web-interface-on-port-9981-and-htsp-9982, an alternative way consists in setting the `TVH_IPV6` environment variable.

I believe IPv6 support should be enabled by default.

**Comment by davidebeatrici** [comment]
For reference: https://tvheadend.org/d/5872-ipv6-accessing-web-interface-on-port-9981-and-htsp-9982

I believe IPv6 support should be enabled by default.
