### ISSUE TITLE
How to support IPv6 network video sources?

### ISSUE THREAD

**Issue by PQ0000** [linuxserver/docker-tvheadend#247]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

How to support IPv6 network video sources?

### Reason for change

How to support IPv6 network video sources?
https://m3u.ibert.me/fmml_ipv6.m3u

**Comment by PQ0000** [comment]
I am using tvheadend in docker, and when I add "- RUN_OPTS='--ipv6'" to the command, I found that the container failed to start. It seems like it is stuck in a loop requesting this command. It seems that this command cannot be used this way.

**Comment by j0nnymoe** [comment]
I believe you need to make sure ipv6 is configured correctly on your docker installation. Unfortunately I don't believe anyone within the team uses IPv6 so it's hard for us to test.

Also need to make sure tvheadend supports ipv6 too.
