### ISSUE TITLE
[FEAT] tv_grab_url should follow redirects

### ISSUE THREAD

**Issue by henrydatei** [linuxserver/docker-tvheadend#258]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change
I'm coming from https://github.com/XMLTV/xmltv/issues/237, they suggested I should ask here.

TVHeadend gives the opportunity to grab XMLTV data with what they call "XMLTV: XMLTV URL grabber". Internally this just calls `tv_grab_url`, a script which uses curl to download XMLTV data from the URL which you provide to the "XMLTV: XMLTV URL grabber". I want to use https://xmltv.info/de/epg.xml as a provider. The problem is now, that this XMLTV provider generates a unique link for every request, so if you request https://xmltv.info/de/epg.xml you get a redirect to https://xmltv.info/de/epg.xml/e4aed9d33f528a05dd3fa1ed2f8b3ef3 and here you get the XMLTV data. After accessing this link is invalid. So for tv_grab_url to function with this provider it needs to follow redirects. 

### Reason for change

see above

### Proposed code change

If you look in the script `tv_grab_url` code you find the line
```
curl -s "$URL"
```
but to follow redirects it should be
```
curl -sL "$URL"
```

**Comment by henrydatei** [comment]
I've asked in the xmltv repo the same question, they said this should be the right place (https://github.com/XMLTV/xmltv/issues/237)

**Comment by aptalca** [comment]
Thanks for the PR. The people who used to maintain this image are no longer using it (or are no longer part of the team) and I'm not too familiar with some of the ancillary functionality that was added here.

But this PR seems sensible.
