### ISSUE TITLE
Unable to sign in using tag latest

### ISSUE THREAD

**Issue by encript** [linuxserver/docker-tvheadend#36]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

I am not able to sign in when using latest tag. Stable tag works fine as there is no user name or password prompt. How may I sign in using latest tag container?

Debian Jessie

docker create \
  --name=tvheadend \
  --net=bridge \
  -v /storage/tvheadend:/config \
  -e PGID=0 -e PUID=0  \
  -p 9981:9981 \
  -p 9982:9982 \
  --device=/dev/dvb \
  linuxserver/tvheadend:latest

**Comment by tobbenb** [comment]
If you wait until tomorrow this will be fixed in the image refresh this night. It's a bug in tvheadend.

If you can't wait, check this post for a solution: http://lime-technology.com/forum/index.php?topic=51621.msg523827#msg523827

**Comment by encript** [comment]
Thank you that worked solution was to create a file named superuser with username and password as described in forum post. Thanks for the point in the right direction.
