### ISSUE TITLE
/dev/dvb has incorrect permissions

### ISSUE THREAD

**Issue by cgrossde** [linuxserver/docker-tvheadend#44]
`/dev/dvb` is owned by root and can't be read by tvheadend which resulted in tvheadend not finding my DVB-C card. Changing permissions of `/dev/dvb` fixed that for me.

```
docker create \
  --name=tvheadend \
  --net=bridge \
  -v /xxx/config:/config \
  -v /xxx/recordings:/recordings \
  -e PGID=1010 -e PUID=1010  \
  -p 9981:9981 \
  -p 9982:9982 \
  --device=/dev/dvb \
  linuxserver/tvheadend
```

Fixed it by:

```
chown -R abc /dev/dvb
pkill tvheadend
```

Running docker 17.03.0-ce with zfs on Ubuntu 14.04.

Is that the way to go or did I miss something?

**Comment by j0nnymoe** [comment]
generally, most people chown the device on the host to correct user on start up before you run the docker, But what ever way works for you :). Glad you have it working.

**Comment by j0nnymoe** [comment]
For reference: https://www.linuxserver.io/2017/02/19/how-to-set-up-tvheadend-with-your-dvb-t2-receiver/

**Comment by tobbenb** [comment]
We should add it to the readme. I was too unraid minded when I wrote the readme :p

**Comment by j0nnymoe** [comment]
Use a cronjob to run a script to set the permissions before the container starts up

**Comment by gurabli** [comment]
This is what I did :)
It looks it is working. Now to find out why I can't stream to android tvh client...

**Comment by henfri** [comment]
Hello,
how do I run a cronjob before the container starts up?
The container is started automatically by docker.

Greetings,
Hendrik

**Comment by 13** [comment]
Working udev rule:
cat /etc/udev/rules.d/90-dvbdocker.rules 
`ATTRS{vendor}=="0x1ade", ATTRS{device}=="0x3038", RUN+="/bin/chown -R ben:users /dev/dvb"`

**Comment by ParadiseStudios** [comment]
> Working udev rule:
> cat /etc/udev/rules.d/90-dvbdocker.rules
> `ATTRS{vendor}=="0x1ade", ATTRS{device}=="0x3038", RUN+="/bin/chown -R ben:users /dev/dvb"`

@13 Can that script be copied and pasted into any debian linux udev? What do the vendor and device ids relate to?

**Comment by aptalca** [comment]
I'll open this again. We do have a method to fix the permissions inside the container to make it work. We implemented in plex, and I'll PR here fro tvheadend. It works on most distros that rely on the default udev rules, owning /dev/dvb by the video group.

**Comment by tobbenb** [comment]
I thought we did add it here, but I guess that was Plex.

**Comment by henfri** [comment]
Why was this closed again?

**Comment by aptalca** [comment]
The issue was fixed in the linked PR

**Comment by henfri** [comment]
Now I seee

**Comment by henfri** [comment]
I see. Thanks

**Comment by ParadiseStudios** [comment]
The udev did not fire off on server restart for me (Debian 10) I had to manually chown again and restart tvheadend.
