### ISSUE TITLE
Unable to play recorded program through webgui

### ISSUE THREAD

**Issue by dpdpkpcom** [linuxserver/docker-tvheadend#65]
First of all, GREAT work with TVHeadEnd docker container - very impressed !

This MAY be a TVHeadEnd issue in which case, sorry for wasting your time.

I run 4.3-861~g715a4a844 on a Synology DS918+

All works fine, and recordings are playable through KODI etc... But not playable through the webgui.....

Clicking the webgui play button next to a recording downloads a file. Clicking the file opens Ubuntu's video application which says "The film could not be read". Opening the file in VLC Media Player says :- VLC is unable to open the MRL blah blah blah.....

The error in the logs on TVHeadEnd is :-

2018-01-03 10:49:23.882 [ ERROR] http: 192.168.1.100: HTTP/1.1 GET /dvrfile/e815d3e1369052572096a9f7f8eb1230 -- 500

Hope this helps you guys.....

Thank you

dp

**Comment by tobbenb** [comment]
I know about the issue already, but it's a bug in TVheadend (or maybe Alpine Linux as it's working in Ubuntu). I haven't filed a bug report yet. I'll try to get the time to do it.
In the meantime, use Kodi to playback recordings.

**Comment by dpdpkpcom** [comment]
Wow, quick response, thanks. Not knowning whose domain the bug was in, I had filed the same bug report on TVHeadEnd's issue tracker - http://www.tvheadend.org/issues/4827. Thanks again

**Comment by tobbenb** [comment]
I'll post there so they know a little bit more about the OS in the container.

**Comment by thenktor** [comment]
Same problem here:
`2018-01-07 11:58:31.876 [  ERROR] http: 10.xxx.yyy.zzz: HTTP/1.0 GET /dvrfile/c55aab6ca6d31d878e1e7a0d2d6ec147 -- 500`

Therefore I cannot play recordings on iPad and Apple TV.

I'm using net=host.

**Comment by dpdpkpcom** [comment]
It's being addressed by both Docker and TVHeadEnd devs I think and I'm impressed with how quickly they are trying to sort it :-)

http://www.tvheadend.org/issues/4827

**Comment by tobbenb** [comment]
@thenktor 
Isn't it possible to use tvhclient on ios?

**Comment by thenktor** [comment]
Same log entry appears when using TvhClient on iOS and tvOS.

**Comment by tobbenb** [comment]
Then you just have to wait until it's fixed or install kodi.

**Comment by vistalba** [comment]
Same issue here :( Is there any fix planned? For me it sounds like iconv does not suppot all stuff tvheadend needs.

Log:
`2018-02-13 21:47:06.324 [  ERROR]:http: unable to convert filename 'ASCII//TRANSLIT//IGNORE' to a safe form using charset '2018-02-13_20-30_SomeShow_SomeChasnnel-HD.mp4'`

**Comment by sparklyballs** [comment]
any fix is dependant upon tvheadend devs

**Comment by tobbenb** [comment]
I need to get some time to debug it. The tvheadend dev added more logging for http, but I haven't had time to play with it.

**Comment by vistalba** [comment]
@tobbenb @sparklyballs
Thanks for response.
I‘m happy if someone works on this :-) thank you. 

is it a issue on tvheadend side or only with docker? As I understood is, that this happens only on alpine?

**Comment by tobbenb** [comment]
It's most likely tvheadend. If not tvheadend, it's alpine.

**Comment by vistalba** [comment]
I think the problem is the alpine package. 

https://tvheadend.org/issues/4940
