### ISSUE TITLE
OTA-EPG grabber fails in build 136

### ISSUE THREAD

**Issue by wrzlbrmpft** [linuxserver/docker-tvheadend#68]
Hey guys, 

first of all thank you so much for mainaining your superb range of docker linuxservers, including the tvheadend one here which has been working flawlassly so far!

Unfortunately, in my SAT>IP setup (Digibit R1 with satip-axe firmware), the current release-4.2 build (tagged 136) does provoke some sort of error when running the OTA-EGP grabber. The webif then does not show any input stream status any more, clients cannot connect and eventuelly the log will get flooded with messages like
 >  mpegts: too much queued table input data (over 2MB), discarding new. 

This was, however, the only kind of error message after the initial log showed my 4 satip receivers tuning into the first epggrab locations. 

I did then revert to build (tag) 135, which works flawlessly and OTA-EGP grabbing finished without problems. 

My docker is running on a Debian Stretch host (Xeon E3-1220V2) with Linux kernel 4.9.0-4-amd64 (#1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux). 

I would very much appreciate any input into how to fix this. 

Best, wrzlbrmpft

**Comment by tobbenb** [comment]
Is it the same build of tvheadend in both 135 and 136?
You could also check if it works in the latest tag, but be sure to backup the config first, as it installs tvheadend 4.3.

**Comment by wrzlbrmpft** [comment]
Thanks for your quick reply! It also looks like I misinterpreted what tags 135 and 136 actually refer to...:

My current logs (container tagged 135) showed:
>  config: backup: migrating config from 4.2.5-14\~g1665c355c (running 4.3-905~g9bed2c7a4)

So what I actually did when replacing the newest release-4.2 build (pulled on 2018-01-14, the faulty one that I wrongly believed to be tagged 136) with tag 135, was an upgrade from the 4.2 branch to 4.3.

I have now also tested the "latest" tag (this runs 4.3-943~g9b85e7b7c) and that one works well during OTA-EPG grabbing, too. 

So all in all: the most recent release-4.2 does show an error during OTA-EPG grabs, the 4.3 branch is fine in that regard.

**Comment by tobbenb** [comment]
I don't think you can go back to a previous version on the release-4.2 tag, as we tag it.
Best option now is to check the tvheadend site and see if anyone have reported the issue. If not, you should report it so it can get fixed.

**Comment by wrzlbrmpft** [comment]
> I don't think you can go back to a previous version on the release-4.2 tag, as we tag it.

Alright, that's what I figured. I'll stay with build 135 for the time being as the tvheadend version in latest (136) has trouble setting up recordings (see [here](https://tvheadend.org/issues/4852)).

> Best option now is to check the tvheadend site and see if anyone have reported the issue. If not, you should report it so it can get fixed.

There are quite a number of recent issues and revisions dealing with the OTA EGP grabber. Mostly with the 4.3 development branch, though. [Bug 4851](https://tvheadend.org/issues/4851) or [4841](https://tvheadend.org/issues/4841) may be connected (although in 4.3, too). 
I'll report there, but according to the 'About' in the TVheadend WebUI the versions in the containers are not built with debugging enabled, so I don't think I could provide a complete crash log easily.

**Comment by tobbenb** [comment]
Did you try to change the time for the EPG grab?

**Comment by wrzlbrmpft** [comment]
Yes, at least sort of... First time it started hanging at 2:04 in the morning (regular cron EPG grabber time). When testing subsequently it hung every time I triggered the grabber from the webif.

**Comment by tobbenb** [comment]
But you never changed the cron time?

**Comment by wrzlbrmpft** [comment]
Well, I actually did change the cron time once to two minutes ahead of the current time and also acknowledged that setting - but then I discovered the button 'Trigger PTA EPG Grabber' and used that (still crashed). 

I think it would be unlikely that such a cron setting could trigger that crash, but if you think this is conceivable I'll try it with changing the cron time only tomorrow.

**Comment by tobbenb** [comment]
It was the fix for the guy reporting bug 4851. That's my reason for asking.

**Comment by wrzlbrmpft** [comment]
I have tested it with a changed cron entry just now: 
first it looked like the grabber would actually run through and the webif stayed responsive - but after three minutes the same thing happened as before (webif unresponsive, errors in logfile: [WARNING] mpegts: too much queued table input data (over 2MB), discarding new).

**Comment by tobbenb** [comment]
I'm going to close this one as it's not a docker issue, but tvheadend issue.
Jaroslav said in his comment on the tvheadend issue that this is a side effect of a bug that eats the CPU.
