### ISSUE TITLE
Recording a Program causes memory usage to grow and grow.....Memory Leak ?

### ISSUE THREAD

**Issue by dpdpkpcom** [linuxserver/docker-tvheadend#70]
Recording a Program (or more than 1) causes memory to grow and grow at a rate roughly equivalent to the data being read from the stream and being written to disk (3MB every 2 seconds)
Megasat Sat>IP3 used as the source (in case it's relevant)

Synology DSM 6.1.4-15217 Update 5
 

No errors in the logs at all.

No symlinks

**Comment by tobbenb** [comment]
This isn't really an issue with the container, but with tvheadend. Needs to be reported to the tvheadend guys, but there might already be a bug filed.

**Comment by dpdpkpcom** [comment]
Hi Tobbenb

In response to me logging this at the TVHeadEnd github as an issue (http://tvheadend.org/issues/4867), Jaroslav has suggested trying with the "latest" branch. So, I'll maybe wait for you guys to update the container (which I think you do weekly), and then "docker pull" the latest one.

Thanks

dp

**Comment by tobbenb** [comment]
I remember seeing that bug actually.
The container will be updated on Friday night UK time. 

Docker pull just downloads the latest image. You also need to update the tvheadend container created when you do the docker create command.

**Comment by upchui** [comment]
Why is it that the cosed? The problem still exists even on X64 until the OEM killer kills the process!
