### ISSUE TITLE
Memory Leak in 4.3-1006~gd381d71e3

### ISSUE THREAD

**Issue by dpdpkpcom** [linuxserver/docker-tvheadend#71]
When a program is recording, memory usage increases at a rate 1:1 proportional to the size of the video feed from my Sat>IP tuner.

I'm pretty sure this is a TVHeadend issue and have reported it with them (https://tvheadend.org/issues/4896), but they are asking me to do something that may require additional tools in the docker image.

Could these tools be added to the image and if not, could you explain how I can help them debug it ?

Here's Jaroslav's message :-1: 
Could you verify, if the memory is malloc()ated ? https://stackoverflow.com/questions/2564752/examining-c-c-heap-memory-statistics-in-gdb

All of the above is using the latest linuxserver docker image as of 28th Jan 2018.

Thanks !

dp

**Comment by tobbenb** [comment]
Sorry, didn't see the issue until now. I'll give you some directions on how to debug it. Just need some time to write it down.

**Comment by dpdpkpcom** [comment]
No problem !

Thank you !

dp

**Comment by tobbenb** [comment]
Can you please test with a fresh pull and check if this is still a problem?
