### ISSUE TITLE
Init stops at 30-config: executing

### ISSUE THREAD

**Issue by failx1993** [linuxserver/docker-tvheadend#72]
Hello guys,

i wanted to run you docker image at my home server.
I created a docker-compose for it:

  tvheadend:
    image: linuxserver/tvheadend
    hostname: tvheadend
    restart: always
    volumes:
      - ./tvheadend/config/:/config
      - ./tvheadend/rec/:/recordings
    environment:
      - PGID=1000
      - PUID=1000
    networks:
      core_net:
         <PRIVATE THINGS>

But the init process stops at:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...

after that nothing is happening an web gui is not reachable.

I also tried to direct run the image with: 
docker run -d \
  --name=tvheadend \
  --net=bridge \
  -v /home/docker/docker/tvheadend/config/:/config \
  -v /home/docker/docker/tvheadend/rec/:/recordings \
  -e PGID=1000 -e PUID=1000  \
  -p 9981:9981 \
  -p 9982:9982 \
  linuxserver/tvheadend

same issue.

I am using tag latest.

**Comment by j0nnymoe** [comment]
What's your host OS?

**Comment by failx1993** [comment]
Oh sorry, its Ubuntu 16.04.3.
But i seems there was a very long delay...after 1 hour the 30-config process was done but after that the log is full with messages like this:

2018-01-30 15:42:35.801 [  ALERT] CRASH: Fault address 0x3e8000003d2 (N/A)


By the way, way fast support :)

**Comment by tobbenb** [comment]
Are you using official docker install or the one in ubuntu?

**Comment by failx1993** [comment]
Docker ppa.

**Comment by tobbenb** [comment]
So it's this one, right?
[https://docs.docker.com/install/linux/docker-ce/ubuntu/](https://docs.docker.com/install/linux/docker-ce/ubuntu/)

**Comment by failx1993** [comment]
yes, exactly.

**Comment by tobbenb** [comment]
Then I don't know what is happening. 
Youcould try the 4.2 release tag and see if the same thing happen there.

**Comment by waja** [comment]
I'm also affected by this.

Right after spinning up the container looking around __INSIDE__ the running container:
```bash
root@foo:/$ ps aux
[...]
  182 root       0:00 bash /var/run/s6/etc/cont-init.d/30-config
  185 root       0:00 chown -R abc:abc /config /picons
root@foo:/$ ls -la /picons/ | grep root | wc -l
5458
root@foo:/$ ls -la /picons/ | grep root | wc -l
4056
root@foo:/$ ls -la /picons/ | grep root | wc -l
4056
[...]
root@foo:/$ ls -la /picons/ | grep root | wc -l
3913
root@foo:/$ ls -la /picons/ | grep root | wc -l
2633
root@foo:/$ ls -la /picons/ | grep root | wc -l
2029
root@foo:/$ ls -la /picons/ | grep root | wc -l
1643
root@foo:/$ ls -la /picons/ | grep root | wc -l
557
root@foo:/$ ls -la /picons/ | grep root | wc -l
2
root@foo:/$ ps aux
PID   USER     TIME   COMMAND
    1 root       0:00 s6-svscan -t0 /var/run/s6/services
   30 root       0:00 s6-supervise s6-fdholderd
  186 root       0:00 bash
  316 root       0:00 s6-supervise tvheadend
  441 abc        0:00 /usr/bin/tvheadend -C -c /config
  454 root       0:00 ps aux
```
This took 5 minutes on my system, so it seems you needed to just wait. But until now I did not debug further why this takes so long.

**Comment by Roger53** [comment]
Great detective work waja, you are 1 millimeter away of a workaround, let me bridge the "gap"

( I use Armbian on Orange Pi One)

The picons folder contains over 5700 files, taking the 6 minutes to chown every time the container is started, as you found out 

So I added :     -v my_picons_folder:/picons \
and filled that folder with my only 150 ish icons

You can pick the icons manually or automated with with https://github.com/reuab/picons-source / but that is out of scope of this issue.

I cant see a startup delay anymore.

So what needs to be solved by the lsioarmhf/tvheadend guys

- dont chown the picon files
or
- dont put 5700 picon files in the image, certainly not in 1 folder
or
- just explain this workaround on your Repository pages

Thanks guys !

**Comment by Roger53** [comment]
Hi tobbenb,

Right, I indeed did not notice that this issue is about a X86 repo, as my search machine found it for me and this was exactly my problem, and helped me to workaround the problem as described.

I am also using Docker-ce (18.03.0-ce) on Ubuntu 16 (Welcome to ARMBIAN 5.38 stable Ubuntu 16.04.4 LTS 4.14.18-sunxi) so yes a lot of similarities with above.

I think modern arm and X86 are not so different as many think anyway, except e.g. performance and the amount of available docker images. ;-(

For that I applaud the linuxserver guys !

**Comment by thelamer** [comment]
We have integrated changes to help alleviate this. Please pull from latest or release-4.2 if you are running into this.
