### ISSUE TITLE
Add socat or netcat to container?

### ISSUE THREAD

**Issue by hidefog** [linuxserver/docker-tvheadend#86]
Hi,

Would it be possible to add socat or netcat to this container?  I am attempting to write guide data to xmltv.sock.  But, the busybox version of nc does not support writing to sockets.
I'd like to be able to do one of the following;
`cat xmltv.xml | socat - UNIX-CONNECT:/config/epggrab/xmltv.sock`
or
`cat xmltv.xml | nc -w 5 -U /config/epggrab/xmltv.sock`

Thanks :)

**Comment by tobbenb** [comment]
You can use the tv_grab_file to import the xmltv file. Go to the settings of tvheadend, then under epg grabber modules, enable tv_grab_file.
Place the xml file in /config/data (create the folder if it's not there) for it to be picked up by the grabber.

**Comment by hidefog** [comment]
Thanks.  That works, too.  I am mostly trying to optimize the process of pulling and importing guide data.
I also found that I can write the data to the xmltv.sock outside of the docker container and it still works.
