### ISSUE TITLE
Latest does not get updated anymore?

### ISSUE THREAD

**Issue by frenos** [linuxserver/docker-tvheadend#90]
Hey,
the "latest" tag for the 4.3.xx version has not been rebuild for a month now. Only the old 4.2 gets a new build every week. Is there anything that blocks an updated 4.3 container and can we help get it fixed?

(The reason I ask is there is a sat epg bug in the current lsio-container 4.3 that has been fixed in the 4.3-git version in the meantime)

**Comment by tobbenb** [comment]
It doesn't compile on alpine linux, which the base image is based on. I filed a bug report about it, but there was only one guy, not a developer of tvheadend, that asked me to test his fix. Haven't done so yet, but will tomorrow.

**Comment by wiserain** [comment]
In my opinion, this PR https://github.com/tvheadend/tvheadend/pull/1133 should be merged to clear current compile error on alpine linux, but maintainer has been inactive since 22 Jun. Maybe he is on leave? I am just waiting.

**Comment by tobbenb** [comment]
I think Jaroslav is on a well deserved vacation. I'm sure he will merge it when he is back.

**Comment by wiserain** [comment]
I guess he's back, and build error is resolved as well.

**Comment by j0nnymoe** [comment]
and built :)
