### ISSUE TITLE
permissions for sat>ip

### ISSUE THREAD

**Issue by henfri** [linuxserver/docker-tvheadend#92]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Hello,

thanks for your great containers!
Host: Debian

Command:
```
docker run \
  --name=tvheadend \
  --net=host \
  -v /srv/Daten/dockerconfig/tvheadend:/config \
  -v /srv/DataPool/Video/TvHeadend:/recordings \
  -e PGID=1 -e PUID=1  \
  --device=/dev/dri \
  --device=/dev/dvb \
  linuxserver/tvheadend
```

for sat>ip tvheadend needs to be run as root, I think. Otherwise the port 554 is not being used by tvheadend and it reverts to a port that can be used by non-root users (9983).

That is why I set PID and GID to 1.

When I do that though, my dvb devices are not showing in tvheadend anymore though. 
On the host, I have set these permissions:

> root@homeserver:~/Docker/tvheadend# ls -l /dev/dvb
> insgesamt 0
> drwxrwxrwx 2 root video 120 Aug  4 10:07 adapter0
> drwxrwxrwx 2 root video 120 Aug  4 10:07 adapter1
> drwxrwxrwx 2 root video 120 Aug  4 10:07 adapter2
> drwxrwxrwx 2 root video 120 Aug  4 10:07 adapter3

And in the container I see:

> root@homeserver:/$ ls -l /dev/dvb
> total 0
> drwxr-xr-x 2 root root 120 Aug  4 10:40 adapter0
> drwxr-xr-x 2 root root 120 Aug  4 10:40 adapter1
> drwxr-xr-x 2 root root 120 Aug  4 10:40 adapter2
> drwxr-xr-x 2 root root 120 Aug  4 10:40 adapter3
> root@homeserver:/$ ps aux |grep tvh
>   201 root       0:00 s6-supervise tvheadend
>   204 bin        0:00 /usr/bin/tvheadend -C -c /config
>   295 root       0:00 grep tvh

Why is tvheadend not running as root and how can I change this?
Or alternatively: what would you recommend me to do?

Regards,
Hendrik

**Comment by tobbenb** [comment]
Tvheadend is not running as root for security reasons.

I'm a little bit confused about what you are using. Satip does not create a /dev/dvb device as it's IP based. Looks like you are using a dvb pcie card.

For now, you need to change the permissions of the /dev/dvb device so the user you set for tvheadend has read/write access.

**Comment by henfri** [comment]
Hello,

thanks for your reply.
Sorry for expressing myself unclear.

I use a dvb pcie card as source and I want to make it available via 
a) HTSP Streaming (works)
b) SAT>IP (does not work)
Here, TVheadend shall be the SAT>IP server (and not a Sat>IP client). [1]

According to the readme on github:

> Tvheadend offers the HTTP (VLC, MPlayer), HTSP (Kodi, Movian) and SAT>IP streaming. 

And in fact that is true. It just does not work with the docker-container as it is.

What happens:
TVH sees that it is not running as root. For that reason it cannot use the default port (554) as it is below 1024. Thus it reverts to a port > 1024 (9983). Unfortunately, all SAT>IP Clients I know do not allow changing the port. Thus, I have a SAT>IP server that cannot be used.

I see only the solutions:
a) to run TVH as root. And as I do not expose my server to the Internet, that is ok for me.
b) not using net=host. Your minisatip container does this:

```
-p 8875:8875 -p 554:554 \
-p 1900:1900/udp
```
This means, that minisatip must be running as root. Don't you see the same security concerns there?
But for TVHeadend, this would work:
```
-p 8875:8875 -p 554:**9983** \
-p 1900:1900/udp
-p 9981:9981 \
-p 9982:9982 \
```
So, we accept that a port >1024 is used *in* the container, but on the host it is mapped to the right port 554.
I am just uncertain, whether that works, because:

> If you use IPTV, SAT>IP or HDHomeRun, you need to create the container with --net=host and remove the -p flags. This is because of a limitation in docker and multicast.
(from the Readme of this container)
I am just not convinced this is right, as it would also apply to your minisatip-container, no?

In any case: The Readme says, what I want to do, but currently, it is not possible.

> For now, you need to change the permissions of the /dev/dvb device so the user you set for tvheadend has read/write access.

Isn't that the case? I chmodded it to 777, see my ls -l output above.

Greetings,
Hendrik

[1] Reason why I need to have TVH as SAT>IP Server: https://github.com/catalinii/minisatip/issues/437, last two posts.

**Comment by CHBMB** [comment]
You need to run our satip container then.  That will make your DVB card appear as a satip device in tvheadend.

**Comment by henfri** [comment]
Hello,

as outlined in [1] this does not work. TVHeadend is a bit special when it comes to Sat>IP: It wants a *specific* adapter via SAT>IP. If this is used by another client TVH will complain instead of using another adapter.
Thus, TVH should be the SAT>IP server. And according to the readme, this should work. But as outlined above, it does not.

Could you please help me understand, why SAT>IP works with the minisatip container without net=host and why for the TVH-Container it is said that net=host is needed if TVH shall be SAT>IP server?

Regards,
Hendrik

[1] Reason why I need to have TVH as SAT>IP Server: catalinii/minisatip#437, last two posts.

**Comment by CHBMB** [comment]
It does work I have done so myself.  Mini-satip to convert the DVB card to a sat-ip device and then it's picked up in TVH.  TVH can't function as a SAT>IP server as far as I know.   Satip does not require host networking as you directly pass the DVB card with ` --device=/dev/dvb` TVheadend requires host networking to pick up the satip stream.

I use satip myself with tvheadend, have done with both a DVB card in the past and now with a Digibit R1 flashed with `catalini/minisatip`

**Comment by CHBMB** [comment]
Apparently I'm wrong, TVH can indeed work as a SATIP server TIL....

in that case, change the permissions on your DVB card with something like

```chown -R $DOCKERUSER:$DOCKERGROUP /dev/dvb
chmod -R 777 /dev/dvb```

then pass it through to your TVH container with `--device=/dev/dvb` and run it using host networking.

**Comment by henfri** [comment]
Hello,

ok, I spent 3h on this now. 
> Mini-satip to convert the DVB card to a sat-ip device and then it's picked up in TVH.
As I outlined in [1] and in my post above, what you describe is undisputed. The problem comes if other devices than TVH want to access the same (minisatip) server.  Please, accept that or read the source I quote. The developer of minisatip confirms this.

> Satip does not require host networking as you directly pass the DVB card with
Passing the DVB-Card not the reason why I think that net=host is needed.

In fact, I am successful getting the dvb cards into tvheadend (just not when trying to run it as root).

The reason why I think that net=host is needed **when trying to run tvheadend as server** is:
https://github.com/linuxserver/docker-tvheadend/blob/master/README.md#host-vs-bridge

> If you use IPTV, SAT>IP or HDHomeRun, you need to create the container with --net=host and remove the -p flags. This is because of a limitation in docker and multicast.

It's the readme of this container!

On the contrary, the linuxserver/minisatip image does NOT state this. Nevertheless, without net=host also this image does not work for me:
https://github.com/linuxserver/docker-minisatip/issues/14


So, still:
running this image and using TVH as a sati>ip server does not work.

Greetings,
Hendrik

**Comment by j0nnymoe** [comment]
Personally I have never used tvheadend as a satip server myself. I have run in the past minisatip and currently run minisatip on my DigibitR1 and I have my tvheadend container set as host. I believe there are more ports than just 554 that TVH uses for running satip. 

Is it an issue for you that you have to use host networking?

**Comment by henfri** [comment]
Hello,

thanks for your reply.
I am happy to use host networking.
The problem is:
If tvheadend is not starting as root, it cannot use a port <1024.
But SAT>IP clients search for servers on port 554.

So, when not using net=host, I can redirect the port with the "-p" option of docker. But with net=host this is not possible.

In the tvheadend forum, it is suggested to *start* tvheadend as root and use the -u option

> Then run your Tvheadend install as root, so you can use lower port numbers. You should also be able to pass "-u" option to Tvheadend so that it will drop to a lower privileged user, but allowing the initial port binding to occur still.

How can I do that with this container?
It requires two things:
a) start tvh as root
b) pass that parameter "-u"

Greetings,
Hendrik

**Comment by tobbenb** [comment]
The -u option is not an option as s6 overlay will not monitor the tvheadend process anymore as the -u option daemonize the process.

Might be able to set permissions so ports below 1024 is accessible though.

Regarding host mode, it's needed when doing multicast, as it doesn't work with bridge mode. This is caused by limitations in docker.

**Comment by henfri** [comment]
Hello,
that's a pitty.

> Might be able to set permissions so ports below 1024 is accessible though.
Even if that is possible, I think that TVH is not checking whether <1024 is accessible, but it is checking whether it is running as root.

>Regarding host mode, it's needed when doing multicast, as it doesn't work with bridge mode. This is caused by limitations in docker.

I understand that. But your minisatip container is not using net=host and should have the same problem then, no?

In fact I think it does... https://github.com/linuxserver/docker-minisatip/issues/14
I'm just surprised I am the first to notice. With TVH my usecase might be exotic, but for minisatip this is the only usecase. So either noone is using the minisatip container, or it must work somehow.

I see two possible way forwards:
a) run tvh as root (why not, if it is not exposed to the net?)
b) redirect 9983 to 554 on the host. Is this possible with iptables or even with docker?

Greetings,
Hendrik

**Comment by henfri** [comment]
Hello,

I did find a SAT>IP client that allows me to change the port. With that, everything works. So this confirms that I only need to redirect the port.

I tried this: 
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport rtsp -j REDIRECT --to-port 9983
(which someone else with the problem posted in his blog)

But this does not help. Is there a speciality with docker which makes this not work?

**Comment by henfri** [comment]
See also:
https://forums.docker.com/t/redirect-port-with-net-host/55487

**Comment by tobbenb** [comment]
What happens if you use port 9983 in the tvheadend satip settings and the map it to port 554 on the host?
So -p 554:9983

**Comment by henfri** [comment]
I think that does not work with net=host, does it?

**Comment by j0nnymoe** [comment]
I don't think there is anyway we can have satip without host networking. This is due to not only port 554 but the fact satip uses multicast aswell. We will change the minisatip documentation to state that it needs host networking rather than bridge but in regards to tvheadend, I am unsure what you want us to do as you mentioned it does work with host networking.

**Comment by tobbenb** [comment]
@henfri What happens if you run it in bridge and use port 9983 in the config and map the port like I said?

**Comment by henfri** [comment]
Hello,

@j0nnymoe: regarding minisatip and the limitation: Understood and agreed

> I am unsure what you want us to do as you mentioned it does work with host networking.

I am totally happy with host networking.
It is just that we need to get satip to be accessible via 554

@tobbenb 
> What happens if you run it in bridge and use port 9983 in the config and map the port like I said?

You mean:

```
docker run \
  --name=tvheadend \
  --net=host \
  -v /srv/Daten/dockerconfig/tvheadend:/config \
  -v /srv/DataPool/Video/TvHeadend:/recordings \
  -e PGID=666 -e PUID=666  \
  -p 554:9983 \
  --device=/dev/dri \
  --device=/dev/dvb \
  linuxserver/tvheadend

```
When I run that, I get:

> WARNING: Published ports are discarded when using host network mode

The ports are not mapped.

Greetings,
Hendrik

**Comment by j0nnymoe** [comment]
@henfri what client are you using for satip?

**Comment by henfri** [comment]
Hello,

as Client I use dvb-viewer ([link](http://www.satip.info/sites/satip/files/files/SETUP_SATIP.zip)) and "Elgato-Sat-IP" (Android). Furthermore I use vdr (linux).
@tobbenb sorry: In bridge I had:
docker run \
  --name=tvheadend \
  --net=host \
  -v /srv/Daten/dockerconfig/tvheadend:/config \
  -v /srv/DataPool/Video/TvHeadend:/recordings \
  -e PGID=666 -e PUID=666  \
  -p 554:9983 \
  -p 1900:1900/udp \
  -p 9981:9981 \
  -p 9982:9982 \
  -p 8875:8875 \
  --device=/dev/dri \
  --device=/dev/dvb \
  linuxserver/tvheadend

This did not work at all (even in dvb-viewer in which I can change the port), which seems to confirm that SAT>IP requires host.

Greetings,
Hendrik

**Comment by j0nnymoe** [comment]
@henfri ok thanks for the client info - I can get the windows dvb viewer working on my desktop with my satip device (DigibitR1) but I am unable to get the android client working with this.

Atleast I have something to try out and I will see what I can find.

Quick question, any reason why you can't export the m3u playlist from tvheadend and use that?

**Comment by tobbenb** [comment]
@henfri 
This all depend on what the satip server/client use to transport the stream. It supports both unicast and multicast. I think RTSP is unicast, so then it can work in bridge mode.
What you need to do is to find out which other ports is used and then add port mappings. You can add a range, if you find out which range it uses.

**Comment by henfri** [comment]
Hello,

> What you need to do is to find out which other ports is used and then add port mappings. You can add a range, if you find out which range it uses.

I think that will not work as the Client is selecting the ports ([link](https://www.vdr-portal.de/forum/index.php?thread/128014-satip-plugin-client-ports/#post1306742))

So, why not root?

Greetings,
Hendrik

**Comment by henfri** [comment]
Hello,

I cannot find a port range in the [specification](http://www.satip.info/sites/satip/files/resource/satip_specification_version_1_2_2.pdf).
Also I do not think that it would be good reserving a large range of ports.

So, to summarize up to here:
-We know it would work if we ran as root.
-We do not know whether there is a chance getting it to work in bridged mode
-As non-root it would be ok with net=host, but we need to make sure that we redirect the port from 9983 to 554.

Greetings,
Hendrik

**Comment by tobbenb** [comment]
I'm not talking about checking the specifications, but trying it out and see which ports are used. Or do you prefer others does the tests for you? 

Tvheadend is not going to run as root in this container.

**Comment by henfri** [comment]
Hello,

why do you think that trying out is better than checking the specification?
According to other sources, the port is random by design. So there is little point trying.

Why is Tvheadend not going to run as root in this container and what do you suggest otherwise?
The only alternative solution I see is trying to redirect the ports manually on the host using iptables (which is the same docker is doing, but not when net=host). I tried that as shown above, but it did not work.

Greetings,
Hendrik

**Comment by tobbenb** [comment]
![unknown](https://user-images.githubusercontent.com/10107585/43690294-45d78702-9908-11e8-89c6-3019cf0f77b9.png)

The ports are set by the client by the looks of this. I think this might be dvbviewer. 
So it might not be as random as you have heard. 

It doesn't seem like you want to listen to my suggestions.

**Comment by henfri** [comment]
Hello,

thanks for your reply. 
Specifying the ports is possible in some clients, but that is the exception, not the rule. 
Again: I do not think that we should work against the Spec which specifically and intentionally uses random ports.

> It doesn't seem like you want to listen to my suggestions.

If 'listen' means to blindly follow and execute, you are right.
If 'listen' means to match your suggestions with my own knowledge then you are not right.

With the first approach we have one brain working, with the second two. I prefer that. 
I reckon I could mirror that comment. I suggested the root approach and the iptables approach several times without getting proper feedback.

Let's both try to improve.

Greetings,
Hendrik

**Comment by tobbenb** [comment]
I don't find anything in the specifications about random port numbers. It's the client that sets which port to use for the stream. I don't know which client you are using, but should be possible to find out which ports it uses. 
I don't really have the time to set it up and test this myself as this is not my paid job, and I'm doing this in my limited spare time.
I'm asking you to do some tests to see if we can find away around the limitations.

Why can you only run satip?

**Comment by henfri** [comment]
Hello,

I did check the ports:

```
root@homeserver:~/Docker/tvheadend# netstat -an | grep 168.177.20 |grep -v 81 | grep -v 22
tcp        0      0 192.168.177.3:445       192.168.177.20:53164    VERBUNDEN
root@homeserver:~/Docker/tvheadend# netstat -an | grep 168.177.20 |grep -v 81 | grep -v 22
tcp        0      0 192.168.177.3:445       192.168.177.20:53164    VERBUNDEN
tcp        0      0 192.168.177.3:554       192.168.177.20:53700    VERBUNDEN
udp        0      0 192.168.177.3:5506      192.168.177.20:52042    VERBUNDEN
udp        0      0 192.168.177.3:5507      192.168.177.20:52043    VERBUNDEN
root@homeserver:~/Docker/tvheadend# netstat -an | grep 168.177.25 |grep -v 81 | grep -v 22
tcp        0      0 192.168.177.3:554       192.168.177.25:54182    VERBUNDEN
udp      704      0 192.168.177.3:5502      192.168.177.25:56387    VERBUNDEN
udp        0      0 192.168.177.3:5503      192.168.177.25:56388    VERBUNDEN
```

Yes, the client sets the port for the stream. But it is random. The two examples are (IP .20) with DVB-Viewer and (IP .25) Elgato Sat>IP.

You will now say, that I shall forward port 5502 till 5510. But that's trial and error. The next client will use another port. It may solve my problem, but it is not general.

> Why can you only run satip?

What else could I? I think it it is a wider spread standard than TVHeadend.

I have solved my problem by patching the run root/etc/services.d/tvheadend/run and removing 
s6-setguid.

I know, that you do not like running this as root. But I ask you to consider it. I think this is the only proper solution (except for a manual forwarding with iptables, which I could not get to work).

I would suggest adding an optional env-variable to run the container as root.

Greetings,
Hendrik

**Comment by tobbenb** [comment]
What are your clients?
The best option for tvheadend is to use a client that support HTSP protocol, which is tvheadends own.
If you use a PC or RPI, install Kodi  or libreelec and enable the tvheadend plugin. This way you also get EPG from tvheadend.
On your phone you could use tvhclient and use mxplayer or vlc for playback. Android media players can run kodi. You could also use Emby for all platforms but need a PC for the server.

If you need to run VDR, I don't think they have any tvheadend plugins. But isn't VDR a PVR backend, the same as tvheadend?

**Comment by henfri** [comment]
Hello,

my clients are:
Elgato Sat>ip (Android)
VDR (linux)

I know that I can use HTSP and I will. But I would like to have a transition phase (good for the family; they can select).
In one year from now, I expect to use "Native" TVH-Clients everywhere.

But let's not focus on my problem, but on the fact that this docker image has a limitation.
Can we agree that the two proper options to solve this are 

> I know, that you do not like running this as root. But I ask you to consider it. I think this is the only proper solution (except for a manual forwarding with iptables, which I could not get to work).

?
And then let's see how we can implement one of the two.

Greetings,
Hendrik

**Comment by thelamer** [comment]
I have reviewed the information in the thread and do not believe there is any reason to keep this open. 

We will not be running the pid as root, it rubs against the core of all of our application design and ownership for stuff in containers. 

As far as I can tell 9983 will be the only port this will ever run on in our Docker container as even if we setcap the check in Upstream's code is for what the PID of the user executing is. (feel free to report this upstream to support setcap then maybe down the line we can support it) 

If you personally need to run this as root I recommend you mount in a custom run like this: 
`-v /path/to/my/custom/script:/etc/services.d/tvheadend/run` or use a docker mod to have a replacement script: https://github.com/linuxserver/docker-mods

**Comment by henfri** [comment]
Hello,

thanks for your reply.
What do you mean by 
"setcap the check in Upstream's code is for what the PID of the user executing is. (feel free to report this upstream to support setcap then maybe down the line we can support it)"?

I suggest to add how to run this docker with SAT>IP into the Documentation then.

Regards,
Hendrik

**Comment by thelamer** [comment]
The program cannot run on 554 , the detection logic they use does not take into account a non root user executing a binary that has had it's permissions modified to allow it to listen on ports under 1024 (setcap)
If they instead caught an error of trying to listen on that port and then use alternative ones it would work in this scenario . 
As far as documentation what would you reccomend ? A mention of host vs bridge is in there , do we really need to specifically mention port 9983?

**Comment by foxy82** [comment]
> If you personally need to run this as root I recommend you mount in a custom run like this:
> `-v /path/to/my/custom/script:/etc/services.d/tvheadend/run` or use a docker mod to have a replacement script: https://github.com/linuxserver/docker-mods

Hi - sorry for commenting on an old issue but this comes up as the most prominent issue in a google search when looking to try and get tvheadend on docker with Sat IP working. Can you post an example of how to do either of the above? I think perharps the docker-mods might be the best way to go to allow others to use it?
