### ISSUE TITLE
Missing DVB Setup Instructions (e.g. for Ubuntu LTS versions 14 / 16 / 18 ...)

### ISSUE THREAD

**Issue by Bonifatius94** [linuxserver/docker-tvheadend#93]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
### Problem Description

First I would like to honor your great efforts for this project. It's really great work. Thank you very much.

Now to my problem: I'm trying to get your docker image running using a DVB PCIe TV Card (I know it's a bit old school, but well ...). Getting IPTV to run is very simple and easy, but DVB is the issue.

I've been installing my DVB driver successfully (tested on the host system with w_scan and found channels as expected). That works so far. (I can say that because I've also installed tvheadend manually on another partition on the same PC and everything works fine there.)

Then I downloaded your docker image and installed it with following command:

docker create   --name=tvheadend   --net=bridge   -v ~/tvdata/config:/config   -v ~/tvdata/recordings:/recordings   -v /dev/dvb/adapter0:/dev/dvb/adapter0   -v /dev/dvb/adapter1:/dev/dvb/adapter1   -e PGID=1000    -e PUID=1000   -p 9981:9981   -p 9982:9982   --device=/dev/dri  --device=/dev/dvb  linuxserver/tvheadend

command for starting the image is: docker start tvheadend

Reasons for changes: I needed to add '-v /dev/dvb/adapter0:/dev/dvb/adapter0   -v /dev/dvb/adapter1:/dev/dvb/adapter1' and add the groups 'docker', 'video' and 'www-data' to my docker user (media) in order to make TV Headend recognize my DVB adapters and make docker and the TV Headend website http://localhost:9981 working. (I would be very grateful for a smarter solution.)

Now I've started to configure everything using the TV Headend website (where everything looked fine), but when I tried to scan for channels nothing is found. My conclusion to this behaviour is that the TV Headend process inside the docker image has insufficient permissions for /dev/dvb and I cannot figure out how to fix this issue. There is also very little information about how to map /dev/dvb correctly. I've tried to chown -R /dev/dvb by the media user and stuff, but nothing did work for me until now.

So I would suggest to provide a guide on how to get DVB running on Ubuntu 18 LTS properly. I could also help you with writing the documentation and doing the testing if you wish to.

Thank you very much for your help in advance. I'm looking foreward to getting this docker image to work.

### System Information

Host OS: Ubuntu 18 LTS
Docker User: media (id=1000, with additional groups 'docker', 'video' and 'www-data')
DVB Card: TBS 6522 (dual tuner with 2x DVB-S/S2 and 2x DVB-T/T2 or DVB-C)

### Additional System Information:
ls -la /dev/dvb/adapter0
insgesamt 0
drwxr-xr-x  2 root root     140 Aug 18 12:36 .
drwxr-xr-x  4 root root      80 Aug 18 12:36 ..
crw-rw----+ 1 root video 212, 0 Aug 18 12:36 demux0
crw-rw----+ 1 root video 212, 1 Aug 18 12:36 dvr0
crw-rw----+ 1 root video 212, 3 Aug 18 12:36 frontend0
crw-rw----+ 1 root video 212, 4 Aug 18 12:36 frontend1
crw-rw----+ 1 root video 212, 2 Aug 18 12:36 net0

##  Thanks, team linuxserver.io

**Comment by Bonifatius94** [comment]
Never mind. Got DVB to work by starting my docker image this way:

sudo chown -R $USER:$USER /dev/dvb && docker start tvheadend

**Comment by tobbenb** [comment]
Yes, you need to give the user you use for tvheadend read and write access to /dev/dvb.
So far we don't have any automation to add the abc user to the same group as the host use for /dev/dvb. 

We also don't have any plans to make a guide for setting up tvheadend. We have one generic one on linuxserver.io. 

I thought we had info about changing permissions in the Readme, but apperently we forgot.
