### ISSUE TITLE
add epg for russian channels

### ISSUE THREAD

**Issue by toleeck** [linuxserver/docker-tvheadend#96]
is it possible in the future update of the docker for TVH to add an EPG for Russian channels?

There is an exce﻿llent working file. which, when the docker is updated, has to be added to the manual each time (dsm synology 6.2).
grabber-file I had attached to this message.
[tv_grab_ru.zip](https://github.com/linuxserver/docker-tvheadend/files/2378729/tv_grab_ru.zip)
this TV program is perfect for Russian service iptv edem.tv.
In this TV program there are all federal TV channels that you can use for your viewing and for other services. In addition to the actual TV program, there are links to the logos of TV channels.

**Comment by buzzzzer** [comment]
Why you use epg.it999.ru source ?  teleguide.info source more popular in ru community.

workaround:
enable internal webgrab+plus grabber on tvh settings

on host:
wget -qO - http://epg.it999.ru/edem.xml.gz | gunzip > path_to_tvheadend/config/data/guide.xml

**Comment by tobbenb** [comment]
I have missed this issue. Sorry about that.
I do not like to add grabbers not in the xmltv package as it gets hard for us to keep it updated. 
You could do as buzzzzer says or map the grabber you want to use as a volume mapping.
