### ISSUE TITLE
Duplicate Recordings

### ISSUE THREAD

**Issue by scouseman** [linuxserver/docker-tvheadend#97]
I am using Debian 9 and the lastest docker-tvheadend container, I have never experienced this problem before when I have manually built TVHE.
I have set up a series record, to record the 'News at 10' on BBC1, but it appears to duplicate the recording on random days at the same time on the same channel. It seems very random.

![duplicate recordings](https://user-images.githubusercontent.com/12296640/46238034-7589de80-c380-11e8-80c5-3587f93770fd.PNG)

![seriesrecord](https://user-images.githubusercontent.com/12296640/46238039-7c185600-c380-11e8-913d-81903e03548a.PNG)

Any idea what is causing this

**Comment by homerr** [comment]
Afraid not and not something I've seen. Have you posted on the TVH forums?

**Comment by tobbenb** [comment]
Is this still an issue on a fresh pull?
