### ISSUE TITLE
Picons don't load

### ISSUE THREAD

**Issue by gurabli** [linuxserver/docker-tvheadend#98]
I'm having some hard time to make picons work. I mapped /picons to host, and added the picons there. TVH finds the picons, but they are not displayed in EPG view or Kodi.
Any idea where to start investigating?
Thanks

**Comment by fayn2010** [comment]
It seems I have the same issue. Picons are added in the "Channel / EPG" Tab and the Imagecache number is also increasing if you reset the image cache, however when opening the Imagecache URL direktly, I always getting a 404 file not found error. Maybe some file permission error?

**Comment by fayn2010** [comment]
I found a solution for myself with the following settings. After that you might need to reset the icons in the "Channel / EPG" Tab.  

<img width="723" alt="bildschirmfoto 2018-10-27 um 10 10 01" src="https://user-images.githubusercontent.com/15176413/47601420-a6d1ea80-d9d0-11e8-9bb2-5ac98bac88f2.png">

**Comment by thelamer** [comment]
Created a pull for this issue. https://github.com/linuxserver/docker-tvheadend/pull/110

**Comment by daald** [comment]
The Readme file (which can be seen on https://hub.docker.com/r/linuxserver/tvheadend) should be updated according to the screenshot.
And if wonder if it's possible to remove spaces by default from the icon names (because the default picons don't contain them)

**Comment by tobbenb** [comment]
Why is it needed to add something to the Readme? The picon settings is set up automatically at first boot.

We use the picons from picons.xyz and the names comes from them.

**Comment by daald** [comment]
1) there is already information, but it is wrong. just setting the path to "/picons" results in 404 errors
2) my tvheadend config is older than this feature, that's why I have to do some things manually from time to time

about the names:
if I empty the user icon field of a channel or click "reset icon", it automatically gets a new value, for example "file:///picons/das%20erste%20hd.png". But such a file doesn't exist. instead, it should be "file:///picons/daserstehd.png"

**Comment by tobbenb** [comment]
1. There is no information to set it only to /picons. There is information about where to adjust the settings.
2. We provide basic information for how to get this container to run, not how to set everything up. Refer to the tvheadend documentation for this.

Regarding the names, this is tvheadends domain and not something we have control over. We just package tvheadend into a container.

**Comment by daald** [comment]
1. it's a usability topic. saying "set the Channel icon path in Configuration --> General --> Base to "file:///picons/%C.png" " doesn't feel painful.

regarding the names: so what's the usual procedure? removing %20 from all channel icon paths manually? where does the /picons.tar.bz2 come from?

**Comment by tobbenb** [comment]
Feel free to make a PR for the readme.

Picons are from picons.xyz as mentioned in the Readme.

**Comment by thomas-mc-work** [comment]
> Why is it needed to add something to the Readme? The picon settings is set up automatically at first boot.

Migrating from a bare metal instance is a use case.

**Comment by thomas-mc-work** [comment]
> update: after starting a new tvheadend instance and copying the full block of config values from there it seems to work now, the default names don't have spaces anymore

@daald Could you please post the correct values? I didn't manage to get rid of the spaces for the lookup. Thanks in advance!

**Comment by thomas-mc-work** [comment]
Got it with your screenshot!

For other readers: You can reset an existing icon url in the `Configuration` -> `Channel / EPG` tab (the last button in the toolbar: `Reset icon`)

**Comment by tobbenb** [comment]
> > Why is it needed to add something to the Readme? The picon settings is set up automatically at first boot.
> 
> Migrating from a bare metal instance is a use case.

That is something we don't test. We do not want to fill the readme with too much information. Setting up the picons should be looked up in the tvheadend documentation. The info in our readme is for getting the container up and running and not for configuring tvheadend.

**Comment by daald** [comment]
> That is something we don't test. We do not want to fill the readme with too much information. Setting up the picons should be looked up in the tvheadend documentation. The info in our readme is for getting the container up and running and not for configuring tvheadend.

Why not writing it to a secondary documentation. It's still a difference from the tvheadend original settings, this is reason enough to be documented. Or just a link to that tvheadend documentation which I can't find. I only found two forum topics. but the path prefix `file:///picons/` is clearly specific to this image anyway.

**Comment by tobbenb** [comment]
> > That is something we don't test. We do not want to fill the readme with too much information. Setting up the picons should be looked up in the tvheadend documentation. The info in our readme is for getting the container up and running and not for configuring tvheadend.
> 
> Why not writing it to a secondary documentation. It's still a difference from the tvheadend original settings, this is reason enough to be documented. Or just a link to that tvheadend documentation which I can't find. I only found two forum topics. but the path prefix `file:///picons/` is clearly specific to this image anyway.

It's mentioned in the readme what the path to the picons are. The rest should be looked up in the tvheadend documentation, which is available in thveadend by clicking the help button. It's also the second hit on Google if you search for tvheadend documentation. https://docs.tvheadend.org/

We also have a short guide for setting up tvheadend with a dvb-t2 device in our blog, that also mentions picons setup.
https://blog.linuxserver.io/2017/02/19/how-to-set-up-tvheadend-with-your-dvb-t2-receiver/

We welcome all PRs, so feel free to open one of there is something missing. It does not guarantee that we will accept the PR though.
